dhis2/ui

- packages/widgets/src/Layer/Layer.stories.js
- packages/widgets/src/MenuItem/MenuItem.stories.js
- packages/widgets/src/MultiSelect/MultiSelect.stories.js
- packages/widgets/src/SingleSelect/SingleSelect.stories.js
- packages/widgets/src/Tooltip/Tooltip.stories.js
I noticed that certain components did not have the prefixes that the others all have (`component/widget`). I've added it for the ones that were lacking a prefix. I assumed that this was necessary, so feel free to close if this was intentional.
(The changes in the Layer story are changes made by prettier btw)
> docs: fix storybook prefixes

- cypress/integration/NoticeBox/accepts_children.feature
- cypress/integration/NoticeBox/accepts_children/index.js
- cypress/integration/NoticeBox/accepts_title.feature
- cypress/integration/NoticeBox/accepts_title/index.js
- packages/widgets/src/NoticeBox/NoticeBox.js
- packages/widgets/src/NoticeBox/NoticeBox.stories.e2e.js
- packages/widgets/src/NoticeBox/NoticeBox.stories.js
- packages/widgets/src/NoticeBox/NoticeBoxIcon.js
- packages/widgets/src/NoticeBox/NoticeBoxMessage.js
- packages/widgets/src/NoticeBox/NoticeBoxTitle.js
- packages/widgets/src/NoticeBox/__test__/NoticeBoxIcon.test.js
- packages/widgets/src/NoticeBox/__test__/NoticeBoxMessage.test.js
- packages/widgets/src/NoticeBox/__test__/NoticeBoxTitle.test.js
- packages/widgets/src/NoticeBox/__test__/__snapshots__/NoticeBoxIcon.test.js.snap
This adds the NoticeBox component. See [the design-system entry](https://github.com/dhis2/design-system/blob/master/molecules/notice-box.md), the [latest specs](https://sketch.cloud/s/DwkDk/a/nzvzrk) and [a slack conversation about it](https://dhis2.slack.com/archives/CBM8LNEQM/p1586173863001200).
This is what the component looks like at the moment (screenshots from storybook):
Todo:
Remarks:
- Can't import an outline `<Info>` icon from ui-icons. There are two Info icons being exported, are we overwriting the outlined version maybe?
> feat: add noticebox component

- packages/forms/src/validators/createNumberRange.js
The other validation messages (min and maxNumber) can be left as is in my opinion, they seem easy to understand correctly to me. The tests of createNumberRange are accurate as well. So it's just the wording that I've updated slightly.
See the linked issue for more details.
Closes #13
> fix: update number range validation error to match actual bounds

- packages/forms/src/shared/helpers/getValidationText.js
This fixes the display of field specific submitErrors (see here: [meta.submitError](https://final-form.org/docs/react-final-form/types/FieldRenderProps)). The hasError helper is already dealing with this properly, since it looks at meta.invalid and that's triggered for validation and submission errors.
Using if blocks instead of an expression here for readability, since otherwise it got quite long and difficult to parse. Plus, this only returns the value if it's truthy, slightly different logic, but should be the same in practice (since the values should only be strings and it returns `''` at the end).
I noticed the forms tests aren't being run (or it seems like it): https://dhis2.slack.com/archives/CBM8LNEQM/p1587567537209200. After that's resolved I'll take a look at updating tests …
> fix: display submit errors

- docs/_sidebar.md
- docs/troubleshooting.md
I felt that after spending all that time to get to the bottom of this, we shouldn't forget to add it to the docs somewhere...
> docs(troubleshooting): add info about z-index issue

- packages/icons/package.json
- yarn.lock
See slack here: https://dhis2.slack.com/archives/CPGUFVC56/p1588258220328000
ui-icons uses `@dhis2/prop-types`, but doesn't bundle it. So it defaulted to the top level one, which in my case, was the wrong version. This PR fixes that.
> fix(prop-types): add missing dhis2 prop-types for ui-icons

- docs/_sidebar.md
- docs/concepts.md
Closes #20 
The current state of the `alpha` version lacks proper documentation about structure and motivation.
I've collected several opinions, comments & discussions from github and slack and consolidated them into a single document.
The document is should reflect mostly @varl's perspective right now, I haven't tried to change anything yet and prefer that we talk about some of the strategies and concepts in this PR so we can align our thoughts about what we want this monorepo to be (and not to be!).
Here are the github sources I picked most of the initial contents from:
* https://github.com/dhis2/ui/pull/2
* https://github.com/dhis2/ui-core/issues/794#issuecomment-585082219
* https://github.com/dhis2/ui-core/pull/822#issuecomment-594411581
* …
> Consolidate comments and dicussion

- CHANGELOG.md
There are some things in our changelog that end up making it a bit messy; some missing topics and broken formatting. I've homogenized the formatting and added topics. My intention is to make the changelog as useful as possible for a dev who wants to know exactly what changed in v5.
To that end I've also removed things that were later reverted or refactored. I'm a bit hesitant to do this, but my reasoning is that this will be confusing to the reader because the change didn't actually make it into the release.
Us merging these changes will of course not update the changelog in the past (so for all the commits preceding this merge), but it seems better than nothing to me. For the future it's probably good to pay close attention to this (our commit messages), we already do, but apparently …
> docs(changelog): format changelog manually

- cypress/integration/Popover/arrow_position.feature
- cypress/integration/Popover/arrow_position/index.js
- cypress/integration/Popover/clicking_outside.feature
- cypress/integration/Popover/clicking_outside/index.js
- cypress/integration/Popper/accepts_different_reference_types.feature
- cypress/integration/Popper/accepts_different_reference_types/index.js
- packages/core/src/Popover/Arrow.js
- packages/core/src/Popover/Popover.stories.e2e.js
- packages/core/src/Popper/Popper.js
- packages/core/src/Popper/Popper.stories.e2e.js
This adds some tests to check the arrow positions for the `Popover` and different reference types for the `Popper`. When merged, issue https://github.com/dhis2/ui/issues/83 can be closed.
Along the way I also fixed a few typos and a bug (see commit 209e5be and this issue popperjs/react-popper#354)
> test(popper): additional popper and popover e2e tests

- README.md
Adds a link to the readme for the blogpost, so that it's a bit easier to discover.
> docs(readme): add link to v5 blogpost

- docs/getting-started.md
If we want to add a polyfills section we can always do that later. I don't see any added value in having the TODO there, so I removed it.
The badge was pointing to ui-core, so I fixed that as well.
> docs(getting-started): fix badge and polyfills section

- CONTRIBUTING.md
I've gone through the concepts doc, and I think it's actually not very interesting to our users in its current form. I can see the use of an overview of our libraries, but I think this document is currently written more from our point of view, as developers, not for consumers of the lib.
I propose we remove this section, as in its current state I think it's a bit confusing to lib users, and move it to an issue, where we plan adding a `Developing` section. Then we can rewrite where necessary, and add this section back as an instruction to developers that want to contribute.
> docs(concepts): remove concepts

- docs/advanced-usage.md
Ref: #119
This adds the styled-jsx override example from https://github.com/dhis2/notes/pull/110 here. It's advanced usage, and discouraged, but we've received enough question about it that we should document it clearly somewhere, so that the dangers are also clear to everyone.
Closes: https://github.com/dhis2/notes/pull/110, https://github.com/dhis2/notes/issues/108
Note: I think that Viktor wanted to add this override somewhere else. I think I saw a PR or issue where he added this. So consider this a proposal, we should take a look at if this matches what Viktor wanted to do as well.
> docs(styled-jsx): add documentation on styled-jsx override

- docs/_sidebar.md
I forgot to update the sidebar links, I thought these were automatically generated but they're not.
> docs(sidebar): update sidebar links

- packages/core/src/Select/Select.js
I forgot to add a check to make sure the select has been mounted before accessing `offsetWidth`, which at times leads to this error:
This fixes that error.
> fix(select): check if select has been mounted before accessing ref

- packages/forms/src/SwitchFieldFF/SwitchFieldFF.js
- packages/widgets/src/SwitchField/SwitchField.js
My earlier fix unearthed a different issue, namely that we're passing `input.checked` to the Switch's `value` prop. According to the MDN docs on the [checkbox input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox), the input property is just for specifying a string that will be submitted to the backend if the checkbox is checked. Final-form seems to comply with this as well:
> https://final-form.org/docs/react-final-form/types/FieldProps
So instead of `checked` we should be passing `value` here. I see we already do this with the RadioFieldFF and CheckboxFieldFF, so I think this was just a typo.
> fix(switch): use input value instead of checked for the value

- packages/widgets/src/Transfer/Filter.js
- packages/widgets/src/Transfer/Transfer.js
- packages/widgets/src/Transfer/Transfer.stories.js
Fixes #131 
Adds a `placeholder` to the `Filter` in the `Transfer` component, as per [TECH-395](https://jira.dhis2.org/browse/TECH-395).
-----------------
_Story example: Filtered_
-----------------
_Story example: Custom Filtering With Filter Input_
> feat(transfer): add filter placeholder (TECH-395)

- packages/widgets/src/Transfer/RightHeader.js
- packages/widgets/src/Transfer/Transfer.js
- packages/widgets/src/Transfer/Transfer.stories.js
Fixes #90
Adds a `rightHeader` to the `Transfer` component, as per [TECH-394](https://jira.dhis2.org/browse/TECH-394).
-----------------
_Story example: Header_
_Story example: Custom Filtering With Filter Input_
> feat(transfer): add rightHeader (TECH-394)

- packages/widgets/src/Transfer/Transfer.js
- packages/widgets/src/Transfer/Transfer.stories.js
Fixes #105 
Fixes [TECH-393](https://jira.dhis2.org/browse/TECH-393)
Adds a `selected` prop (bool) to the `Transfer` component's `renderOption`. This enables consumers to use `selected` in the `renderOption` function to provide separate styles for the source options and picked options, in addition to the already existing `highlighted` prop.
-----------------
_Story example: Custom List Options_
> feat(transfer): add prop selected to renderOption (TECH-393)

- package.json
- packages/core/src/Table/Table.js
- packages/core/src/Table/Table.stories.js
- packages/core/src/Table/TableContext.js
- packages/core/src/Table/TableRow.js
- packages/core/src/Table/TableRowHead.js
Fixes #207 
Fixes TECH-416
Adds the `alternateRowBgColor` prop that defaults to true.
Can be set globally on the `Table` component and/or individually on `TableRow` components.
> feat(table): add alternateRowBgColor prop (default: true) (TECH-416)

- packages/core/src/ButtonStrip/ButtonStrip.js
- packages/core/src/ButtonStrip/ButtonStrip.stories.js
Fixed #92 
I've also changed the prop type of `children` to `propTypes.node`, because a prop types error is thrown when providing only one child
> fix: remove margin of first child conditionally for correct alignment

- package.json
- packages/core/package.json
- packages/forms/package.json
- packages/ui/package.json
- packages/widgets/package.json
- yarn.lock
This moves internal dependencies (as well as external dependencies which operate as singletons) to peerDependencies.
Technically this is breaking, but since it was incorrect to include these as runtime deps in the very recent v5 release I think it's OK (gulp) to release this as a fix.
> fix: move internal and singleton dependencies to peerDependencies

- docs/getting-started.md
Hey 👋 
This PR adds a small section in the getting started section. This is because while we were updating the `capture-app` to use the `@dhis2/ui` we got into the scenario that we had to install as peer dep the `styled-jsx` 
Happy to hear your feedback on the text :)
> docs(getting-started): adds text for peer dependency installation 

- packages/core/src/Radio/Radio.js
See Jira issue with link to codesandbox: https://jira.dhis2.org/browse/DHIS2-9104
When clicking a radio in a modal that is scrollable, the modal will scroll and the content will be outside of the viewport. This is due to how the modal is scrolling the modal-content only, using `display: flex`. I believe the reason for using flex here is to keep the header above the content when scrolling. 
The Card rendered by the Modal will have a height of something like 2x of the modal-content. So when a Radio is clicked, the page is for some weird reason (see https://stackoverflow.com/questions/24299567/radio-button-causes-browser-to-jump-to-the-top/24323870)  scrolled to the position of the clicked Radio in the `Card-div`. As far as I understand this, it's due to the `position: absolute` on the …
> fix(radio): modal jumping when clicking radio

- packages/core/src/MenuItem/MenuItem.js
Before this fix, `onClick` could get a `false` value for disabled items, and that would trigger an error.
Now `onClick` can only be a function, or `undefined`, and that should take care of the error.
> fix(menu-item): make sure onClick is undefined when disabled

- packages/widgets/src/Transfer/LeftSide.js
- packages/widgets/src/Transfer/RightSide.js
- packages/widgets/src/Transfer/common/index.js
- packages/widgets/src/Transfer/common/styles.js
This PR adds background color properties to the transfer option containers. Previously they were transparent, which was incorrectly stated on the design spec.
> fix: add background to transfer option containers

- packages/core/src/TextArea/TextArea.styles.js
Closes #274 
I'm using regular white, just like our Input.
> fix: use white background color for textarea instead of transparent

- packages/core/src/IntersectionDetector/IntersectionDetector.js
- packages/widgets/src/Transfer/OptionsContainer.js
- packages/widgets/src/Transfer/useResizeCounter.js
Fixes #257 
* Removed the `observer` variable in the `IntersectionDetector` which caused buggy behavior
* Restructured the combination of resize + intersection to not call the `onEndReached` callback twice in the beginning
> fix(transfer): make inifinite loading work when selecting options (#257)

- packages/widgets/src/MultiSelectField/MultiSelectField.js
- packages/widgets/src/SingleSelectField/SingleSelectField.js
Closes #266 
Our SingleSelectFields and MultiSelectFields were emitting a warning in the console when hovering over their label. This is because of a faulty `name` that was being passed to the `Field` component. It's not present in the props, so the global `window.name` was passed (`""`). That's also why it didn't show up in linting (since window.name exists).
Our select is not a labelable component (https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable), so I've removed the name line from the SingleSelectField and MultiSelectField.
> fix: remove name property for select field labels

- packages/core/src/Button/Button.stories.js
- packages/core/src/Button/Button.styles.js
Fixes https://github.com/dhis2/ui/issues/273 by adding opaque backgrounds to disabled buttons of type `primary` and `destructive`.
> fix(button): adjust disabled styles

- packages/widgets/i18n/en.pot
- packages/widgets/src/OrganisationUnitTree/RootError.js
Closes #279 
I've also made the message part of the translation so that it can be positioned differently for languages that are rtl for example (though I assume they'd still have problems with the error message text itself).
> fix: use > as ns separator for translation with :

- packages/core/src/Menu/Menu.js
- packages/core/src/Menu/Menu.stories.js
This relates to #176. We are dealing with two things here:
- A potentially confusing feature, hiding the divider from the menu-section-header if it's the first child of a menu. In most cases I think this behaviour does make (some) sense and it's possible to "opt out" of this behaviour by explicitly setting `hideDivider` to `false`.
- A bug in the implementation of this feature.
Currently all I've done in this PR is to fix that bug, and introduce an example of the feature.
However, I'd also be fine removing the feature. It seems to be causing more confusion than it brings convenience.
Let me know what you'd prefer.
> fix(menu): stop using child's dense prop to set value of hideDivider

- packages/forms/src/InputFieldFF/InputFieldFF.js
The type property is only accessible through the `input` prop that's passed to the InputFieldFF component, so it needs to forward that property. The `input.type` property is undefined when no type is provided, so I just forwarded the prop and ignored the missing type case (which will default to `input` in the `Input` component)
> fix(input field ff): forward type property of Field component

- packages/widgets/src/OrganisationUnitTree/OrganisationUnitNode.js
- packages/widgets/src/OrganisationUnitTree/OrganisationUnitTree.js
- packages/widgets/src/OrganisationUnitTree/OrganisationUnitTree.stories.js
- packages/widgets/src/OrganisationUnitTree/__e2e__/tree_api.stories.e2e.js
- packages/widgets/src/OrganisationUnitTree/__tests__/useOrgData.test.js
- packages/widgets/src/OrganisationUnitTree/useOrgData.js
- packages/widgets/src/OrganisationUnitTree/useOrgData/helpers.js
Fixed DHIS2-9440
I've added a `suppressAlphabeticalSorting` in case this behavior is not wanted, sorting now happens by default.
It'll change the order of displayed items in apps that already use this, but as apps don't have any control over this process, this won't break anythings, so in my opinion this does not need to be a breaking change.
> feat(orgunittree): sort org units alphabetically

- packages/core/src/Button/Button.styles.js
This PR adjusts the padding on icon-only buttons for regular and dense sizes.
Previously the left/right padding was too large, causing icon-only buttons to be slightly-not-square at 38x36 and 30x28. The fix adjusts the css to make the icon-only buttons correctly sized at 36x36 and 28x28.
> fix: adjust icon button sizes

- packages/core/src/AlertBar/AlertBar.js
- packages/core/src/AlertBar/AlertBar.styles.js
Fixes an infinite loop caused by an unconditional setstate on component updates. It doesn't seem necessary to re-run init when the props are updated anyway. The core problem was the setState in the `show()` method, which was called by `init()`, which was run on every update (or more precisely, when state was the same as the previous state).
* Since we're not reusing init, I've just moved what we were doing there to didMount
* Since show was called on didMount and just changing state, I'm now starting with that state on mount. That meant show could also be removed. This meant that the animation logic had to be changed, which I've done as well.
I've tried to stick to the existing code as much as possible. Starting out with the `.visible` class could maybe be refactored to starting out …
> fix(alertbar): skip init on component update

- package.json
Closes #312 
I don't see this package being imported anywhere. The build and storybook also still work after removing. Yarn why shows this:
I think it's safe to remove it. Seems like it's bundled in the app-shell.
> chore(dependencies): remove unused package

- storybook/.storybook/preview.js
- storybook/package.json
- yarn.lock
Replaces deprecated https://www.npmjs.com/package/typeface-roboto with the recommended, maintained follow-up: https://www.npmjs.com/package/fontsource-roboto.
> chore(dependencies): replace deprecated roboto package

- packages/widgets/src/HeaderBar/Apps.js
- packages/widgets/src/HeaderBar/NotificationIcon.js
This PR will allow keyboard focus on the apps drawer trigger in the headerbar. It also changes the focus styles of headerbar items for contrast accessbility.
The current apps drawer trigger is a `<a>` without `href` and therefore cannot be focussed. This (naive) fix uses a `<button>` instead to allow focus, and styles the button to be invisible. I am unaware if there was a reason to use an `<a>` initially that would make `<button>` the wrong choice, but I found no issues when testing.
Fixes https://jira.dhis2.org/browse/LIBS-50
> fix(headerbar): allow keyboard focus on apps drawer trigger

- packages/core/src/Tooltip/Tooltip.js
- packages/core/src/Tooltip/Tooltip.stories.e2e.js
- packages/core/src/Tooltip/features/layering.feature
- packages/core/src/Tooltip/features/layering/index.js
This fixes bug [TECH-473](https://jira.dhis2.org/browse/TECH-473) which @turban reported. I'll provide some info:
- Our layering mechanism can be leveraged in two ways:
1. Adding new layers via the `Layer` component. This will result in a blocking UI because it actually renders a div that covers the underlying content. For a `Tooltip` this isn't good.
2. Using the `useLayerContext` hook to get the closest parent layer root node. You can pass this node as the second arg in a call to `React.createPortal` so that the new portal becomes a direct descendant of the parent layer node and the normal CSS z-index stacking context Just Works ™️ . I hadn't used this approach before but the Tooltip seemed to be the right candidate for it.
- Since the Tooltip was initially a class component it could …
> fix(tooltip): leverage layer context to ensure correct stacking of the tooltip

- packages/core/src/IntersectionDetector/IntersectionDetector.js
`ui-core` has a [dependency](https://github.com/dhis2/ui/blob/master/packages/core/package.json#L29) on `@dhis2/prop-types@^1.6.4`. The re-export style was changed in `@dhis2/prop-types@2.0.0`.  All other components in `ui-core` use the pre-2.0 import style for `@dhis2/prop-types`, but for some reason this one doesn't.
I'm not sure how this component could ever have worked... and curious how we didn't catch this in tests.  The storybook appears to be broken, perhaps related - https://ui.dhis2.nu/demo/?path=/story/intersectionobserver--absolute-bottom-area
We should probably upgrade the dependency and move to the new `@dhis2/prop-types` import style here (codeMod?), or revert the prop-types export change if we're not going to use it.
> fix(IntersectionDetector): use mixed export prop-types style

- packages/constants/d2.config.js
- packages/core/d2.config.js
- packages/forms/d2.config.js
- packages/icons/d2.config.js
- packages/ui/d2.config.js
- packages/widgets/d2.config.js
This fixes our d2-app-scripts entrypoint configuration. We were using `entryPoint`, when the docs reference `entryPoints`: https://platform.dhis2.nu/#/config/d2-config-js-reference?id=supported-properties.
It worked because we were using the default entryPoint (`src/index.js`), which d2-app-scripts falls back to.
> chore(release): fix entrypoint configuration

- .gitignore
- .yarnrc.yml
- netlify.toml
This locks the yarn version that will be used when installing dependencies for this monorepo to 1.19.1.
> chore(yarn): lock yarn version to 1.19.1

- package.json
Icons doesn't have a watch script, so it has been removed from the npm scripts.
> build(icons): fix scripts for ui-icons build

- packages/widgets/src/SharingDialog/AccessSelect.js
- packages/widgets/src/SharingDialog/Autocomplete/Autocomplete.js
- packages/widgets/src/SharingDialog/ShareBlock.js
- packages/widgets/src/SharingDialog/SharingDialog.js
- packages/widgets/src/SharingDialog/SharingList.js
- packages/widgets/src/SharingDialog/SharingListItem.js
- yarn.lock
https://jira.dhis2.org/browse/LIBS-89
> fix: prevent access-before-initialisation storybook errors

- .eslintrc.js
This runs our circular dependency checks only on CI, to not slow down editors, as the checks can be very cpu intensive.
See the GH docs for the `CI` env var I'm using: [GH actions docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables). Besides GH actions, `CI` is a pretty common env var for indicating that code is running on CI so it should even work with most other providers. See also here: https://github.com/watson/ci-info/blob/master/index.js#L52.
Also, as a follow up and if this works out, we can move this and related rules to cli-style and make it a rule we check for all our codebases: https://jira.dhis2.org/browse/CLI-19
> ci(eslint): only run circular dependency check on CI

- .eslintrc.js
- packages/constants/.eslintrc.js
- packages/core/.eslintrc.js
- packages/icons/.eslintrc.js
- packages/ui/.eslintrc.js
- packages/widgets/.eslintrc.js
- The import restriction that prevented imports of `@dhis2/ui` in the root eslint has been moved to the eslint config of the individual packages, so that it doesn't get overwritten.
- Let me know if you think the restrictions are too strict anywhere. Currently this is the hierarchy:
- constants and icons can't import from any other ui packages
- core can only import from icons and constants
- widgets can only import from core, icons and constants
- forms can import from widgets, core, icons and constants
> build(eslint): add more import restrictions

- README.md
This adds a link to the design system, just so it's clear what principles and specs this lib is based on. Noticed during the presentation that we didn't have that yet.
> docs(readme): add link to design system

- packages/core/src/Button/Button.js
It seems like during a refactor of the button component the name attribute was unintentionally omitted. This fixes that and passes the name prop to the button element.
> fix(button): pass name prop to button element

- packages/icons/package.json
The prop-types library is used in the generated react components: https://github.com/dhis2/ui/blob/d7949dad5397c1fe5d1568892c715ded233ec29c/packages/icons/templates/icon-template.js#L16
Also added react and react-dom peer dependencies.
> fix(icons): add missing prop-types dependency

- .storybook/preview.js
- packages/widgets/src/Transfer/Transfer.stories.js
Closes https://jira.dhis2.org/browse/LIBS-100
It seems like using React hooks in Storybook components causes some kind of infinite loop somewhere in the rendering process and so I've had to remove the `InfiniteLoading`, `CustomFilteringWithFilterInput` and `CustomFilteringWithoutFilterInput` stories. I'm not sure why the `useState` in the `withState` HOC doesn't cause any issues though :confused:
> fix(transfer): move from decorator to Component Story Format for Transfer stories

- packages/core/src/MultiSelect/MultiSelect.stories.e2e.js
- packages/core/src/MultiSelect/features/menu_width_matches_input.feature
- packages/core/src/MultiSelect/features/menu_width_matches_input/index.js
- packages/core/src/Select/Select.js
- packages/core/src/SingleSelect/SingleSelect.stories.e2e.js
- packages/core/src/SingleSelect/features/menu_width_matches_input.feature
- packages/core/src/SingleSelect/features/menu_width_matches_input/index.js
See https://github.com/dhis2/notes/discussions/221 for context. I created a story based on the code sandbox @martinkrulltott provided, a feature that reproduced the issue, and a fix that solved it. The solution was actually in the `Select`, which is being used by both the `SingleSelect` and the `MultiSelect`. However, since the `Select` doesn't have any stories, we ended up with a single fix and two (almost identical) stories/e2e-tests.
> fix(select): update menu width when opening

- packages/core/src/Table/Table.js
- packages/core/src/Table/TableBody.js
- packages/core/src/Table/TableCell.js
- packages/core/src/Table/TableCellHead.js
- packages/core/src/Table/TableFoot.js
- packages/core/src/Table/TableHead.js
- packages/core/src/Table/TableRow.js
- packages/core/src/Table/TableRowHead.js
This adds role props to all Table components, so that users can manually set the ARIA role if necessary.
> feat(table): add role attributes for table components

- packages/core/src/Tooltip/Tooltip.js
- packages/core/src/Tooltip/Tooltip.stories.js
- packages/core/src/Tooltip/__tests__/Tooltip.test.js
Allows configuring tooltip open and close delays via `openDelay` and `closeDelay` props to cater to a wider variety of use cases.
Relates to [this question in notes](https://github.com/dhis2/notes/discussions/230)
> fix(tooltip): configure open and close delays via prop (LIBS-126)

- packages/core/src/Checkbox/Checkbox.js
The disabling of pointer events on the input interfered with the accessibility of our checkbox. I've followed the recommendations in this article https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons. The strategy is basically to leverage the behaviour of the native checkbox as much as possible, by positioning it on top of the svg, and just using the svg for display purposes. Instead of depending on the label to capture the clicks, we're now allowing the input to behave as it normally does, and just using the svg to replace the look of the checkbox.
It could be improved a lot more btw, but for now I've just fixed the most immediate accessibility issue. Later on we should apply the recommendations from the article in full for both our checkboxes and …
> fix(checkbox): make checkbox accessible

- packages/core/src/Input/Input.js
- packages/core/src/Input/__tests__/Input.test.js
- packages/widgets/src/InputField/InputField.js
Adds support for adding native `min`, `max` and `step` attributes to inputs in `Input` and `InputField`
Relates to this discussion: https://github.com/dhis2/notes/discussions/240
> feat(input): add min/max/step attr for inputs (LIBS-133)

- packages/core/src/Modal/Modal.js
- packages/core/src/Modal/Modal.stories.e2e.js
- packages/core/src/Modal/features/can_be_closed.feature
- packages/core/src/Modal/features/can_be_closed/index.js
Fixes an issue where modals don't register onClose events when clicked above (or below, for bottom-aligned modals), as seen in this discussion: https://github.com/dhis2/notes/discussions/232
CenteredContent attempts to enable 'clicking through' the container component that applies the positioning rules by disabling pointer events on that container, then re-enabling pointer events on the `centered-inner-content` div that will hold the children.  The issue is that any margins or other space around children in that div will have pointer events enabled, and thus will not click through to content behind the CenteredContent as desired (as seen in the modal example in the discussion above)
~~Adding an `innerContentStyles` prop to CenteredContent that adds styles to `div.centered-inner-content`, …
> fix(modal): close modal by clicking above (LIBS-127)

- .storybook/static/manager.css
- .storybook/static/preview.css
This PR adjusts the design of some elements of the storybook documentation:
- adjusts document link color to meet WCAG AAA
- adds visibly different `:visited` state for document links
- adjusts sidebar headings for readability
Note: I followed the directions for using the [storybook CSS escape hatches](https://storybook.js.org/docs/react/configure/theming#css-escape-hatches), but this still required using `!important` on all rules.
> docs: adjust storybook design

- packages/core/src/Input/Input.js
- packages/core/src/Input/Input.stories.js
Stories were missing for the `Input` component.
Stories in the new format were added, and some descriptions for the component and its props were added as well.
> docs: add stories for input [LIBS-138]

- packages/core/src/AlertBar/AlertBar.js
- packages/core/src/ButtonStrip/ButtonStrip.js
- packages/core/src/Checkbox/Checkbox.js
- packages/core/src/MultiSelect/MultiSelect.js
- packages/core/src/NoticeBox/NoticeBox.js
- packages/core/src/SingleSelect/SingleSelect.js
- packages/core/src/Tag/Tag.js
Files with user-facing stories now mainly use React `prop-types` to work best with storybook doc generation, but a few components still use prop-types from the `@dhis2/prop-types` library.
To differentiate between the two prop type objects in these files (`PropTypes` from React and `propTypes` from dhis2), named imports are used for the dhis2 validators.
> chore: differentiate react and dhis2 prop types when in same file

- .storybook/.babelrc.js
- .storybook/main.js
- cypress.json
- jest.config.js
- package.json
- packages/constants/package.json
- packages/core/package.json
- packages/forms/package.json
- packages/icons/package.json
- packages/icons/src/index.js
- packages/ui/package.json
- packages/widgets/package.json
- yarn.lock
When running `yarn build:icons` on master, the following files are being created:
```
packages/icons/build/es/lib.js
packages/icons/build/cjs/lib.js
```
When switching to this branch, this does not happen anymore until I added an `index.js` to the icons' src folder which imports `./react/index.js`
> chore(cli app scripts): update to 5.7.2 and adjust related files

- packages/core/src/Help/Help.js
This PR changes the color of `warning` and `valid` variations of the `help` component. The previous colors were not [AA accessible](https://www.w3.org/TR/WCAG21/#contrast-minimum). 
I have replaced `theme.valid` and `theme.warning` with the color variables because the theme values are used elsewhere where the contrast requirements are not as strict. I contemplated adding `theme.warning-dark` and `theme.valid-dark`, but I thought that was over-engineering this. I am open to feedback if that would indeed be a better solution. Perhaps `theme.warning-text` might be a useful addition?
> fix(help): accessible colors for help text statuses

- .storybook/preview.js
`addDecorators` and `addParameters` are deprecated - use the new format instead
[[LIBS-145]](https://jira.dhis2.org/browse/LIBS-145)
> chore: update storybook decorators and parameters API

- packages/widgets/src/HeaderBar/Profile.js
One of the main analytics features for 2.36 is the responsive dashboard app. The goal is that the app should look good and have a subset of functionality on phone portrait orientation.  This PR is to make the UserIcon also look correct on phone portrait, since it is part of the overall impression of the responsive dashboard app.
Before:
After:
> fix: enforce min w and h on UserIcon to keep circle shape on small screens [LIBS-151]

- docs/migrating.md
- docs/migrating.stories.mdx
Adds a page to both the docsite and the storybook that links to information about migrating from previous UI versions
> docs: add Migrating page

- packages/core/src/Select/FilterInput.js
This PR fixes the issue shown in the screenshot below where the select options (for both single and multiselects) appear above the filter input.
> fix(select): set z-index to 1 on FilterInput used by selects

- packages/core/src/Modal/Modal.js
Add the ARIA `dialog` role and `aria-modal` attribute (see [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) and [here](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html#rps_label)) to modals to improve accessibility.
> fix(modal): add ARIA dialog role to modals

- packages/core/src/Radio/Radio.js
- packages/core/src/Switch/Switch.js
See: https://jira.dhis2.org/browse/LIBS-162
This changes the inputs on our custom radio and switch input components to accept clicks. If we block clicks on them accessibility is hindered, since that's usually what will be targeted for clicks.
It also sets an appropriate default aria role for the switch, and accepts an aria label. Since a switch sometimes doesn't have a visible label, there should be an aria-label to identify it (https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html).
> fix: address accessibility issues in core components

- .storybook/preview.js
- docs/_sidebar.md
- docs/constants.md
- docs/constants.stories.mdx
Previously it was a little hard to find a reference for color, spacing, elevation, etc. constants in the `ui-constants` package, so I added a page documenting them to the storybook and the docsite.
I also fixed the sidebar in the doc site to link to the 'Migrating' page
> docs: add page about UI constants to SB & docsite (LIBS-142)

- package.json
- packages/constants/package.json
- packages/core/package.json
- packages/core/src/Checkbox/Checkbox.js
- packages/core/src/Input/Input.js
- packages/core/src/Radio/Radio.js
- packages/core/src/Switch/Switch.js
- packages/forms/package.json
- packages/icons/package.json
- packages/ui/package.json
- packages/widgets/package.json
The `merge-alpha-to-master` branch has been branched off my local master, which I merged alpha into (after solving the merge conflicts). Normally I'd just push my master, but that's not possible due to our required status checks on master.
So this seems like the next best thing. I'm not sure if this will mess with history though (for semantic release), so I've requested a review from @varl, to double check if this is our intended way to merge alpha into master.
p.s.: These changes have already been reviewed when they went into alpha (though technically the merge conflict resolutions haven't).
> chore: merge alpha to master

- packages/core/src/DropdownButton/DropdownButton.js
This PR fixes a bug in the `dropdown button` component. The default position of the dropdown content is changed to `bottom-start`, as opposed to `bottom-end`.
> fix(dropdown button): adjust dropdown default position

- .eslintrc.js
- packages/core/src/CssReset/CssReset.stories.js
- packages/core/src/CssVariables/CssVariables.stories.js
- packages/core/src/FlyoutMenu/FlyoutMenu.stories.js
- packages/core/src/Logo/Logo.stories.js
- packages/widgets/src/OrganisationUnitTree/OrganisationUnitTree.stories.js
- packages/widgets/src/Transfer/Transfer.stories.js
- yarn.lock
Follow up for the cli-style v8 PR. This adds global overrides for rules that we've been overriding on an ad hoc basis for stories. Since they don't really make sense for stories, I feel it's cleaner to just disable them globally.
Minor fix is the yarn lock update, which I snuck into this PR, apparently the cli-style alpha was still in there.
> chore(eslint): add global overrides for stories

- d2-style.config.js
- package.json
- yarn.lock
This uses what was introduced in https://github.com/dhis2/cli-style/pull/400 to omit ignored files from the files passed to eslint. This prevents the lint warning you'd otherwise get on running `yarn lint`.
See here for the lint step on CI, which doesn't log any warnings now: https://github.com/dhis2/ui/pull/585/checks?check_run_id=2557102715#step:7:17
Compared to master: https://github.com/dhis2/ui/runs/2547217632#step:7:17 (which usually logs even more if the icons are built)
> chore(d2-style): skip ignored files for linting

- package.json
- yarn.lock
Closes #544
We received a dependabot update for react-dev-utils: https://github.com/dhis2/ui/pull/544. I suspect we don't actually need this module directly. I can't find it referenced anywhere in the codebase.
From the package readme (https://www.npmjs.com/package/react-dev-utils):
> This package includes some utilities used by Create React App. [...] These utilities come by default with Create React App. You don’t need to install it separately in Create React App projects.
I think this dep was introduced here: https://github.com/dhis2/ui/commit/71fe7e94e9690ce3393b9f8e5bf5e6e327d1a6c6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R60 (see package.json)
Yarn why shows this: 
If all the tests pass I think this should be safe to remove.
> chore(dev-deps): remove react-dev-utils

- packages/core/src/Modal/Modal.js
- packages/core/src/Modal/Modal.stories.e2e.js
- packages/core/src/Modal/Modal.stories.js
- packages/core/src/Modal/features/does_not_unmount_children_when_hiding.feature
- packages/core/src/Modal/features/does_not_unmount_children_when_hiding/index.js
Fixed LIBS-182
([link](https://jira.dhis2.org/browse/LIBS-182))
This introduces a new layer: background (= `z-index: -1`).
That was needed to make the layer to into the background when hiding the Modal. Rendering the content in a hidden div instead of the Layer made the components unmount, so that's not an option unfortunately.
This introduces a new prop on the Layer: `transparent` (= `background: none`)
When the modal is hidden and the page does not have a background, the translucent background is still shown. `transparent` prevents that from happening, the prop has a higher priority than `translucent` so both props can be set (see usage of Layer in the implementation of the Modal component)
> feat(modal): add "hide" prop to prevent content from unmounting when hiding (WIP)

- packages/widgets/src/HeaderBar/Profile.js
Also see here:
https://play.dhis2.org/dev/api/schemas/user.json
```json
{
"fieldName": "email",
"simple": true,
"required": false,
"writable": true,
"min": 0,
"nameableObject": false,
"klass": "java.lang.String",
"propertyType": "EMAIL",
"oneToOne": false,
"oneToMany": false,
"propertyTransformer": false,
"attribute": false,
"owner": true,
"readable": true,
"translatable": false,
"ordered": false,
"identifiableObject": false,
"max": 160,
"manyToMany": false,
"length": 160,
"collection": false,
"gistPreferences": {
"included": "AUTO",
"transformation": "AUTO"
},
"analyticalObject": false,
"embeddedObject": false,
"unique": false,
"name": "email",
"namespace": "http://dhis2.org/schema/dxf/2.0",
"persisted": true,
"manyToOne": false
},
```
> fix(header-bar): make email prop optional as in user schema

- components/menu/src/menu-item/menu-item.js
Closes https://jira.dhis2.org/browse/LIBS-191
> fix(menu-item): do not call event.preventDefault() in onClick handler if href prop is set and user is holding meta/alt/ctrl/shift key (alpha)

- components/organisation-unit-tree/src/compute-child-nodes.js
When initially loading an organisation unit, the organisation unit tree will not request its `children` field and so when the `OrganisationUnitNode` component calls `computeChildNodes` (see below) `node.children` will be `undefined` resulting in an error.
https://github.com/dhis2/ui/blob/e21ae4ace1ba8931dd7a5eb0d96ab4f828efe07c/components/organisation-unit-tree/src/compute-child-nodes.js#L27-L38
> fix(organisation-unit-tree): handle filtering when units' children have not yet been loaded

- collections/forms/src/MultiSelectFieldFF/MultiSelectFieldFF.js
Options is not required but if not provided it breaks with ``map does not exist on undefined`` error
Not sure the code style of the library, alternatively mark ``options`` as a required field, however that's change over the API-facing props.
> fix: Add default value for options

- components/loader/src/circular-loader/circular-loader.js
- components/loader/src/circular-loader/circular-loader.stories.js
- components/loader/src/linear-loader/linear-loader.js
- constants/src/shared-prop-types.js
Implements [UX-6](https://jira.dhis2.org/browse/UX-6)
This PR adjusts the loading components, in particular the circular loader:
- simplifies shape and animation to reduce motion, especially when using multiple spinners on a page.
- adds a static background track to improve visibility on varied backgrounds.
- adds an `invert` mode for use on colored backgrounds, (will be used in an upcoming PR to add loading modes to the `Button` component).
- adds an `xsmall` size. (I added this to `sharedPropTypes.sizePropType`, even though `Loader` is the only one using it so far).
- adjusts linear loader for consistency with circular styles.
> feat: loader updates (UX-6)

- docs/forms/react-final-form.md
- docs/forms/validators.md
- docs/recipes/transfer-infinite-loading-all-options-selected.md
The syntax highlighting of some of our documentation was incorrect due to the language being specified as `js` instead of `jsx`.
> docs: use jsx instead of js for code in markdown

- components/button/package.json
- components/button/src/button/button.js
- components/button/src/button/button.stories.js
- components/button/src/button/button.styles.js
Fixes [UX-22](https://jira.dhis2.org/browse/UX-22).
This PR adds a loading state to the `Button` component. The loading state prepends the `CircularLoader` component to the `Button` children. If an `icon` is present, it is replaced by the `CircularLoader`.
This PR also adjusts and adds stories to make testing the loading spinner states easier.
Note: This is my (potentially) naive implementation of how a `loading` state. Please do say if there is a better way of doing this.
> feat(button): Loading state

- components/header-bar/src/notification-icon.js
This PR fixes an issue that was [raised on Slack](https://dhis2.slack.com/archives/CPGUFVC56/p1625056213266600), that the Messages and Interpretations icons were being blocked by notification badges with large numbers.
A discussion took place about removing the numbered badges in favour of other solutions, but no conclusion was reached. Therefore, this PR is a fix to ensure the icons are visible when the existing badges have large numbers.
> feat(header-bar): adjust notification badge placement

- components/alert/src/alert-bar/alert-bar.styles.js
- components/alert/src/alert-bar/dismiss.js
This PR makes changes to the "dismiss" action in the alert bar:
- adds a visible hover state to indicate interaction.
- increases the clickable area to make the action easier to trigger.
> feat(alert bar): increase clickable area for dismiss action

- components/file-input/package.json
- components/file-input/src/file-input/file-input.js
- components/file-input/src/file-list/file-list-item.js
This PR updates the file-input component:
- uses ui-icons instead of embedded SVGs
- uses ui loader instead of custom loading component
> fix(file input): use ui-icons and ui loader

- components/node/src/node.stories.js
- components/organisation-unit-tree/src/organisation-unit-node/organisation-unit-node.js
This PR updates the `node` and `organisation-unit-tree` components with the correct usage of `CircularLoader`.
> fix: change loader sizes for organisation unit components

- components/tooltip/src/tooltip.js
The `tag` prop is being rendered in the documentation as it is included in the default props (though it is unused and not present in propTypes).
> fix(tooltip): remove `tag` from defaultProps

- components/alert/package.json
- components/alert/src/alert-stack/alert-stack.js
- components/layer/package.json
- components/layer/src/index.js
- components/layer/src/layer.js
- components/layer/src/layer.stories.e2e.js
- components/menu/package.json
- components/menu/src/menu-item/menu-item.js
- components/modal/package.json
- components/modal/src/modal/modal.js
- components/modal/src/modal/modal.stories.js
- components/portal/README.md
- components/portal/d2.config.js
- components/portal/package.json
- components/portal/src/index.js
- components/portal/src/portal.js
- components/tooltip/src/features/layering.feature
- components/tooltip/src/features/layering/index.js
- components/tooltip/src/tooltip.js
Introduces a new Portal component that can be used as a standard React
component, either with a default or custom mount point.
Nested Modals in JSX is now an unsupported technique. Modals can be
siblings, but not placed within each other.
If a modal needs to create another modal, then a wrapper component that
controls which of the sibling modals should open and when it should be
used. Modals placed as siblings will render on top of one another based
on the order in the DOM, so last sibling renders on top of the
preceeding ones.
> feat(portal): introduce component

- components/button/src/button/button.styles.js
- components/button/src/split-button/split-button.js
Modifying the z-index on the border causes it to be shown above the
normal stacking context, which causes it to overlay on top of e.g.
modals and component covers.
Generally we should avoid modifying the z-index of components and allow
them to be automatically put into the relevant stacking context.
> fix(button): remove z-index from border style

- components/header-bar/i18n/en.pot
- components/header-bar/package.json
- components/header-bar/src/features/the_headerbar_displays_online_status_when_pwa_is_enabled.feature
- components/header-bar/src/features/the_headerbar_displays_online_status_when_pwa_is_enabled/the_headerbar_displays_online_status.js
- components/header-bar/src/header-bar.js
- components/header-bar/src/header-bar.stories.e2e.js
- components/header-bar/src/header-bar.stories.js
- components/header-bar/src/online-status.js
- components/header-bar/src/online-status.styles.js
- yarn.lock
Fulfills first iteration of [LIBS-48: Display connection status in global interface](https://jira.dhis2.org/browse/LIBS-48)
This PR adds a status badge/bar on mobile to the headerbar that shows 'Online' or 'Offline' and an appropriate icon.
The full spec for the first iteration includes the ability to add additional text beside the online status, which will come in one or more following PR's to keep the scope of this one concise. Also, the status indicator at this stage is in a useful working state.
To add the additional text to the indicator:
> feat: add online status to headerbar

- components/header-bar/i18n/en.pot
- components/header-bar/package.json
- components/header-bar/src/features/the_headerbar_can_display_online_status.feature
- components/header-bar/src/features/the_headerbar_can_display_online_status/the_headerbar_displays_online_status.js
- components/header-bar/src/features/the_headerbar_displays_online_status_when_pwa_is_enabled.feature
- components/header-bar/src/features/the_headerbar_displays_online_status_when_pwa_is_enabled/the_headerbar_displays_online_status.js
- components/header-bar/src/header-bar.js
- components/header-bar/src/header-bar.stories.e2e.js
- components/header-bar/src/header-bar.stories.js
- components/header-bar/src/online-status.js
- components/header-bar/src/online-status.styles.js
- yarn.lock
Part of https://jira.dhis2.org/browse/LIBS-48
Applying this feature will also require some changes to the app platform:
1. to read a configuration option in `d2.config.js` that decides what kind of additional text to add to the online status indicator -- I'm thinking either `headerbar.onlineStatusInfo` or `pwa.headerbarStatusInfo` for the config property, but I'd like a second opinion 🧐 
2. and add that option to the app config through the shell and adapter
> feat: add 'last online' info to status indicator

- components/sharing-dialog/src/autocomplete/autocomplete.js
Editing the search field results in the input field being remounted, which causes focus to be lost.
This PR fixes this by moving the field rendering from a component to a function.
> fix(sharing-dialog): prevent search field remount and focus loss

- components/header-bar/src/online-status.js
- components/header-bar/src/online-status.styles.js
Uses the [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) CSS property to make label and info text unselectable
> fix(header-bar): make online status text unselectable

- components/header-bar/src/features/the_headerbar_can_display_online_status.feature
Sometimes, one of these two tests can fail in CI ([test one](https://dashboard.cypress.io/projects/vyavbk/runs/1790/test-results/851e96cb-7e79-47bc-bbe1-2e9012f21d0b?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D), [test two](https://dashboard.cypress.io/projects/vyavbk/runs/1795/test-results)). I'm working to figure out what's going on, but for now I'll disable them so they don't block other work
> test(header-bar): disable flaky tests for now

- components/button/src/button/button.styles.js
- components/button/src/split-button/split-button.js
- components/checkbox/src/checkbox/checkbox.js
- components/file-input/src/file-list/file-list-item.js
- components/input/src/input/input.js
- components/menu/src/menu-item/menu-item.styles.js
- components/radio/src/radio.js
- components/select/src/select/input-wrapper.js
- components/switch/src/switch/switch.js
- components/tab/src/tab/tab.js
- components/text-area/src/text-area/text-area.styles.js
- constants/src/theme.js
Partially fixes [UX-20](https://jira.dhis2.org/browse/UX-20)
This PR updates the `:focus` styles for all components to establish a standard, consistent focus style. This PR adjusts styles, but does not add keyboard functionality for several items that are current missing it.
For the following elements, `:focus` styles have been added, but it's not possible to actually focus the element. This additional functionality will be covered by another ticket. This applies to `menu-item` and `file-input`.
> feat: update library-wide focus styles

- scripts/build.js
See: https://dhis2.slack.com/archives/CBM8LNEQM/p1631613953060600. Prevents all build processes from running at once.
> chore(build): limit concurrent processes to 5

- collections/ui/package.json
- components/header-bar/package.json
- components/organisation-unit-tree/package.json
- components/organisation-unit-tree/src/organisation-unit-node/use-org-data/use-org-data.js
- components/organisation-unit-tree/src/organisation-unit-tree/use-root-org-data/use-root-org-data.js
- components/sharing-dialog/package.json
- components/sharing-dialog/src/__tests__/ShareBlock.test.js
- components/sharing-dialog/src/__tests__/SharingDialog.test.js
- components/sharing-dialog/src/share-block.js
- package.json
- yarn.lock
https://jira.dhis2.org/browse/LIBS-200, updates ui to app-runtime v3.
Follow up:
> chore(deps): update app-runtime to latest

- components/pagination/src/pagination.js
- components/pagination/src/pagination.stories.js
Let me know:
- Do we need that addiitonal prop? I'm afraid we do since it matches the design specs. I suppose we could allow for hiding it by setting `pageSummaryText` to an empty string too, but that's not very consistent with everything else.
- Is the way we can customise summary text OK?
> feat(pagination): add hidePageSummary prop and story for custom summary

- components/sharing-dialog/src/__tests__/SharingList.test.js
- components/sharing-dialog/src/__tests__/SharingListItem.test.js
- components/sharing-dialog/src/sharing-list.js
The External users sharing setting does not have any effect currently
> fix: remove External users from sharing dialog

- components/sharing-dialog/src/__tests__/SharingList.test.js
- components/sharing-dialog/src/__tests__/SharingListItem.test.js
- components/sharing-dialog/src/sharing-list.js
The External users sharing setting does not have any effect currently
Backport of https://github.com/dhis2/ui/pull/756
> fix: remove External users from sharing dialog [6.x]

- components/table/src/data-table/__tests__/data-table-column-header.test.js
- components/table/src/data-table/data-table-column-header/data-table-column-header.js
- components/table/src/data-table/data-table-column-header/data-table-column-header.styles.js
- components/table/src/data-table/data-table.stories.js
- components/table/src/data-table/table-elements/table-data-cell/table-data-cell.styles.js
- components/table/src/data-table/table-elements/table-header-cell-action.js
- components/table/src/data-table/table-elements/table-header-cell/table-header-cell.styles.js
Closes https://jira.dhis2.org/browse/LIBS-236
This PR replaces the use of fixed height table cells with a less brittle padding-based approach.
The primary benefit of this change is the elimination of overflow-related issues:
| Before | After |
| --------- | ------ |
| ![image](https://user-images.githubusercontent.com/4295266/135469315-8da12318-7917-46c6-8c15-e06e97f17fb3.png) | ![image](https://user-images.githubusercontent.com/4295266/135469187-fbe2b70f-c2c8-4b35-8af3-7bdb6c70ce61.png) |
| ![image](https://user-images.githubusercontent.com/4295266/135469841-09cbd9f0-c9ce-40a3-a3f7-2daaeb24069e.png)  | ![image](https://user-images.githubusercontent.com/4295266/135469738-4437d61e-df22-4d1c-aacd-f75232447b07.png) |
> fix(data-table): use padding instead of fixed cell heights

- components/user-avatar/src/text-avatar.js
As @cooper-joe found out, the previous background color was set to 0.5 opacity. The correct representation of 80 in hex is `cc`.
> fix(user-avatar): use correct hex value for 0.8 background opacity

- components/select/src/multi-select/features/accepts_max_height/index.js
- components/select/src/select/menu-wrapper.js
- components/select/src/single-select/features/accepts_max_height/index.js
This PR adjusts the menu wrapper used by `select`, both `single-` and `multi-` variants, fully fixing [UX-46](https://jira.dhis2.org/browse/UX-46). https://github.com/dhis2/ui/pull/836 fixed this for all other menus using `flyoutMenu`, but the `select`s used a custom menu.
This PR removes the `card` component, which had a `cardClassName`, though it wasn't exposed as a prop. So, removing this doesn't appear to be a breaking change?
> fix(select): adjust menu style

- package.json
- yarn.lock
This updates the app-runtime to the latest version, which includes this fix: https://github.com/dhis2/app-runtime/commit/1b7a42f3592074bbe0fc2798a60b81423159962a. I need that for the sharing-dialog to be able to debounce requests.
> chore(deps): update app-runtime

- components/user-avatar/src/user-avatar.js
This PR adjusts the documentation for the `user-avatar` to clarify the available types (and reflect updated Design System docs). `Icon` fallback is deferred and not implemented yet, and should not be mentioned in the documentation.
> docs(user-avatar): update available types

- components/tooltip/src/tooltip.js
This takes care of a problem that occurs when attaching a tooltip to something that is going to be unmounted. For example a delete button. By clearing the timeouts when unmounting, we prevent a react developer warning regarding potential memory leaks.
I tried to write a test for this, but could not manage it. I was able to reproduce the problem and could see the developer warning in the terminal during the test run. But I wasn't able to create a working spy for this waring function, so I wasn't able to assert the warning is not shown after applying the fix.
> fix(tooltip): clear timeouts when unmounting

- components/tooltip/src/features/positions/index.js
- components/tooltip/src/tooltip.js
- components/tooltip/src/tooltip.stories.e2e.js
This PR makes the following changes to the `Tooltip` component:
- adjusts the colors, sizes and spacings to increase contrast from `8.85` to `14.67`, without increasing the overlall size of the element. Fixes [UX-53](https://jira.dhis2.org/browse/UX-53).
- note: I tried reducing the height hardcoded in the `.feature` for testing, but still failing a couple of tests here. Any pointers what I'm missing here?
- reduces the default `closeDelay` from `400` to `200`, reducing the sense asymmetrical lag.
> fix: tooltip adjustments

- components/sharing-dialog/src/tabs/tabbed-content.js
The type is a required prop, but just for complete consistency with the existing version of the sharing-dialog this now also falls back to the visualization type when type is undefined.
> fix(sharing-dialog): fall back to visualization for undefined type

- components/button/src/dropdown-button/__tests__/dropdown-button.test.js
- components/button/src/dropdown-button/dropdown-button.js
- components/button/src/dropdown-button/dropdown-button.stories.js
The idea is as follows:
- If an `open` prop is provided this component goes into "controlled mode", so the parent component can determine when the `Popper` should render.
- If that's the case, the `onClick` becomes a required prop, because that callback will be needed.
Note:
I noticed one strange thing, only in the tests, which I couldn't really explain and I have had to work around it. I have left a code comment to clarify [here](https://github.com/dhis2/ui/pull/865#discussion_r758343075).
> feat(dropdown-button): add controlled mode

- components/modal/src/modal-actions/modal-actions.js
- components/modal/src/modal-content/modal-content.js
- components/modal/src/modal-title/modal-title.js
Fixes [LIBS-277](https://jira.dhis2.org/browse/LIBS-277).
This PR reduces margins and changes how they are applied. Instead of applying top/bottom margins to `ModalContent`, the respective margins are applied to `ModalTitle` and `ModalActions`. If these elements aren't present, those margins aren't needed (the `Modal` itself has frame padding).
> fix(modal): reduce spacing between elements

- components/button/src/button/button.styles.js
Fixes [LIBS-280](https://jira.dhis2.org/browse/LIBS-280).
This PR adjusts the `Button` `secondary` style to be more visible on various background colors.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/33054985/145196193-1fdfe030-621a-49ce-8f8f-a99d0c97b399.png) | ![image](https://user-images.githubusercontent.com/33054985/145196242-e2a1de68-67ea-443d-affb-3e2f10891903.png) |
Notes
---
**This PR does not fix the issue of this button type being unusable on a dark background**. This is out of scope of this change. Adding a light background to the `secondary` type makes it indistinguishable from the `basic` variant. Potential solutions are an `invert` property, or `dark` theme support.
> fix(button): secondary button contrast

- components/button/src/button/button.styles.js
- components/button/src/split-button/split-button.js
- components/checkbox/src/checkbox/checkbox.js
- components/input/src/input/input.js
- components/radio/src/radio.js
- components/segmented-control/src/segmented-control.js
- components/select/src/select/input-wrapper.js
- components/switch/src/switch/switch.js
- components/text-area/src/text-area/text-area.styles.js
Fixes [UX-20](https://jira.dhis2.org/browse/UX-20). 
This PR fixes focus styles across the library. Focus styles were previously updated, but there were issues where the focus outline was cut off by the parent container. All focus styles are now contained within the element.
For example, issues like:
--- 
| Component | Before | After |
| --- | --- | --- |
| `Button` | ![image](https://user-images.githubusercontent.com/33054985/145997919-89e8e568-53f4-4f8e-b324-fc439909ba65.png) | ![image](https://user-images.githubusercontent.com/33054985/145997718-851d939d-b525-4ea7-86b9-c84eb1d66cf8.png) |
| `Button secondary` | ![image](https://user-images.githubusercontent.com/33054985/145998375-0bcce00c-b4d3-493d-96a7-b4bab787b1e9.png) |  ![image](https://user-images.githubusercontent.com/33054985/145 …
> fix: focus styles

- components/alert/src/alert-bar/alert-bar.styles.js
- components/alert/src/alert-bar/message.js
Fixes [UX-54](https://jira.dhis2.org/browse/UX-54).
This PR prevents alert bars from being cut off on small screens. Small screens in this case is defined down to 320px, which realistically represents the smallest screen that DHIS2 web apps could be used for.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/33054985/146737386-9d67a142-27de-4481-b8b0-711ad822de43.png) | ![image](https://user-images.githubusercontent.com/33054985/146737414-723e6031-7208-4ef4-b4f5-85efbc69da86.png) |
> fix(alert-bar): prevent cutoff on small screens

- collections/forms/i18n/en.pot
- collections/forms/src/validators/__tests__/dhis2Username.test.js
- collections/forms/src/validators/dhis2Username.js
As part of [DHIS2-10886](https://jira.dhis2.org/browse/DHIS2-10886) (see [PR](https://github.com/dhis2/dhis2-core/pull/9358) here), the backend was updated to constrain the range of possible usernames.
This PR updates the username validator in the `forms` collection to match the new restrictions.
> fix(forms): update username regex to match 2.38 backend

- components/table/src/data-table/__tests__/data-table-column-header.test.js
- components/table/src/data-table/data-table-column-header/data-table-column-header.js
- components/table/src/data-table/data-table-column-header/sorter.js
- components/table/src/data-table/data-table.stories.js
This adds a `sortIconTitle` to `DataTableColumnHeader` which makes it possible to configure the sort-button's title. I decided not to add a specific demo for this, because IMO it was quite a logical addition to one of the existing demos. I did add a unit test for both a custom value, and the default.
> feat(data-table): configurable sort icon button title

- components/input/src/input/input.js
Resolves [LIBS-212](https://jira.dhis2.org/browse/LIBS-212), which is a Chrome-specific issue caused by the icon added for `date` and `time` type inputs. The size of the icon has been reduced to fit properly within a `dense` input.
Live example here: https://codesandbox.io/s/chrome-date-time-picker-height-x1f6l?file=/src/styles.css
Example of `text` compared to `date` / `datetime-local` / `time`:
> fix: reduce size of date/time icon in Chrome (LIBS-212)

- components/file-input/package.json
- components/file-input/src/file-input/file-input.js
- components/input/package.json
- components/input/src/input/input.js
- components/select/package.json
- components/select/src/multi-select/multi-select.js
- components/select/src/single-select/single-select.js
- components/status-icon/README.md
- components/status-icon/d2.config.js
- components/status-icon/package.json
- components/status-icon/src/index.js
- components/status-icon/src/status-icon.js
- components/text-area/src/text-area/text-area.js
- components/text-area/src/text-area/text-area.styles.js
Closes https://jira.dhis2.org/browse/LIBS-80
Replaces the margin between various inputs and their status icons with a flexbox gap. Also extracts the `StatusIcon` component.
> fix(status-icon): only apply margin between input and status icon if icon rendered

- components/chip/src/chip.js
This PR allows custom margin values to be passed to the `Chip`. The implementation is based upon the proposal below.
---
Some UI components apply a default margin. For example, the `chip` has a default `margin: 4px`. This was added to provide a reasonable default for the expected usage of a group `chip`s. The alternative, applying no default margin, would mean that in the majority of cases the consumers of UI would need to wrap the `chip` and apply margins.
The default margins applied to some components are not always appropriate. In many cases they are, but in other cases they make the component less flexible. This leads to workarounds that are not recommended, like using `className`. @varl and I have discussed alternatives and have a proposed solution.
Define a standard way for …
> feat(chip): allow custom margin

- components/select/src/select/loading.js
Closes https://jira.dhis2.org/browse/LIBS-283
- Ensures circular loader remains a circle even when loading text wraps
- Adds spacing between circular loader and loading text
> fix(select): don't render circular loader as flex item in order to preserve dimensions

- components/transfer/src/transfer-option.js
Simple fix to allow more customisable Transfer-options. This is used in Data Integrations in the Scheduler app (see https://github.com/dhis2/scheduler-app/pull/348). Label is rendered directly, so a PropType of `node`, should just work.
> fix(transfer): change TransferOption label-proptype to node

- components/pagination/src/__fixtures__/index.js
- components/pagination/src/__tests__/get-item-range.test.js
- components/pagination/src/__tests__/page-controls.test.js
- components/pagination/src/__tests__/page-summary.test.js
- components/pagination/src/__tests__/pagination.test.js
- components/pagination/src/get-default-page-summary-text.js
- components/pagination/src/get-item-range.js
- components/pagination/src/page-controls.js
- components/pagination/src/page-summary.js
- components/pagination/src/pagination.js
- components/pagination/src/pagination.stories.js
This PR adds support to `Pagination` component for pager objects without `total` and `totalPages`. This is relevant because computing the total is expensive and some endpoints have already added support for omitting the totals.
There is some complexity regarding the information we are able still show in the page summary for these pagers without total. 
For example a pager object without a total could look like this:
```
{
page: 2,
pageSize: 50,
isLastPage: false,
}
```
Here we could say `Page 2, items 51-100` and we would know this to be correct, because we know there is a next page, so the current page must have 50 items.
But suppose `isLastPage` would be `false`, i.e.:
```
{
page: 2,
pageSize: 50,
isLastPage: true,
}
```
Now saying `Page 2, items 51-100` is not really correct/accurate. …
> feat(pagination): add support for pagers without a total

- components/sharing-dialog/src/access-add/access-add.js
- components/sharing-dialog/src/autocomplete/sharing-autocomplete.js
- components/sharing-dialog/src/features/add-entity.feature
- components/sharing-dialog/src/features/add-entity/index.js
Before:
https://user-images.githubusercontent.com/150978/157421634-2a3b09cb-1cb4-455c-80a4-13001bac6054.mov
After:
https://user-images.githubusercontent.com/150978/157423660-adfe43fd-46ff-4dd4-a786-3092f3827d57.mov
Before:
After:
> fix(SharingDialog): clear search field once access is granted, fix style

- components/modal/src/modal/modal.test.js
- components/pagination/src/__tests__/pagination.test.js
- components/pagination/src/pagination.js
The main reason for doing this PR is because I remember seeing the page-select completely freezing the browser when there was a huge volume of data. Suppose there are 1,500,000 records and the page size is 50, then the page select would be dynamically populated with 30,000 options and the browser would freeze.  Navigating from page to page is not going to help users find the record they were looking for when there are this many records either. By introducing this max page count limit for showing the page-select, we prevent the browser from freezing...
I see this more of a safety catch type of fix because really if we are dealing with this many records a pager with totals is probably going to cause performance issues on the server as well, so it shouldn't really happen.
Additionally, I …
> fix(pagination): hide page select when only 1 page or too many pages

- components/sharing-dialog/src/constants.js
- components/sharing-dialog/src/sharing-dialog.js
- components/sharing-dialog/src/tabs/tabbed-content.js
Solves [TECH-1037](https://dhis2.atlassian.net/browse/TECH-1037).
`eventVisualization` and `interpretation` are now passed as types to the `SharingDialog` component.
This PR resolves the warnings about invalid prop type.
Before:
> fix(sharing-dialog): support eventVisualization and interpretation types TECH-1037

- components/transfer/src/filter.js
Currently if we have several `Transfer` components on a page we get a warning:
```Found 3 elements with non-unique id #dhis2-uicore-transfer-filter:```
This is because:
a) In `components/transfer/src/filter.js` we pass `name={dataTest}` to our `Input` component
b) Our `Input` component uses the `name` to set as `id`
I think just removing the name prop from the `Input` rendered by the (Transfer) `Filter` makes most sense here, because not populating the input id with the name is going to break the semantic link between the input and the label.
> fix(transfer): do not pass name to input so we don't get duplicate ids on the page

- components/modal/src/modal/modal.js
I caused a regression in https://github.com/dhis2/ui/pull/1013. This PR restores the old styles.
The problem I was trying to solve in the app will start popping up again, but at least the basic auto-overflow functionality will be restored. You can see the regression I caused [here](https://ui.dhis2.nu/demo/?path=/story/layout-modal--middle-scrollable).
> fix(modal): restore auto scroll styles

- components/select/src/single-select/selection.js
- https://github.com/dhis2/notes/discussions/333
- https://dhis2.atlassian.net/browse/LIBS-312
- https://codesandbox.io/s/suspicious-mountain-x4izzr?file=/src/App.js
- https://dhis2.slack.com/archives/CBM8LNEQM/p1650887322458659
As you can see in the screenshot below, the icons are cut off because of the default browser styles of `flex-shrink: 1`:
After the proposed fix (setting `flex-shrink: 0`), the icon area no longer shrinks and remains at 16 x 16:
Because the icon area is 16 x 16, icons larger than that will be cut off. That was already the case before this PR. We could look into accomodating other icon sizes as well in a separate PR. First I think we should address https://dhis2.atlassian.net/browse/LIBS-312 though, and clearly document this bit of API.
> fix: improve selected option icon spacing for select components

- components/select/src/select/input-prefix.js
Before this fix:
After the fix:
> fix: increase prefix spacing so icon is closer to the option text

- collections/forms/src/validators/dhis2Username.js
Relates to [DHIS2-13283](https://jira.dhis2.org/browse/DHIS2-13283)
---
It became apparent that a few of the constraints we have imposed on usernames were not reflected in the error message. The result was that users would see that they entered an invalid user name, but it wouldn't be clear which parts weren't allowed.
> fix(forms): provide a clearer error message if username is invalid

- collections/forms/src/validators/__tests__/dhis2Username.test.js
- collections/forms/src/validators/dhis2Username.js
Implements [DHIS2-13446](https://jira.dhis2.org/browse/DHIS2-13446)
---
We recently implemented a new validation regex on both the server as well as the client, but it turned out to be too restrictive. We are now relaxing things a bit and allowing for lowercase characters too.
> fix(forms): allow upper case characters in dhis2 user name

- docs/docusaurus.config.js
This PR removes the breadcrumb component that was automatically added to generated documentation in Docusaurus beta 16. Breadcrumbs provide no value in our documentation because there are no section-homepages.
---
---
Before: 
After:
> docs: remove autogenerated breadcrumb

- components/tab/src/tab/tab.js
Partly implements [UX-106](https://dhis2.atlassian.net/browse/UX-106)
---
This PR adjusts the tab hover style. The previous style had an issue of looking possibly "greyed out" or disabled. The updated hover style avoids using a grey background. The active style is also updated to avoid a flash of grey background, which is unecessarily distracting. The selected text color is darkened a shade, for contrast (this could've been it's own PR, actually, but perhaps it can be bundled here).
`transition`s are also removed for hover to reduce unnecessary motion, using them only for changing selected tabs.
Note that the hover style is a supporting signifier to indicate interaction. The mouse cursor change is the main signifier.
---
-   [X] API docs are generated
-   [X] Tests were added
-   [X] …
> fix(tab): update hover style

- docs/src/css/custom.css
This PR fixes the missing css import for fonts used in docs. I chose to use [xz/fonts](https://github.com/xz/fonts) rather than Google Fonts.
---
> docs: include webfont import

- components/selector-bar/src/selector-bar-item/selector-bar-item.js
This PR changes the placement of menus opened by `selection-bar-item`s, from `bottom-end` to `bottom-start`.
---
> fix(selection-bar): change menu alignment

- components/menu/src/flyout-menu/flyout-menu.js
See [this Slack thread](https://dhis2.slack.com/archives/CBM8LNEQM/p1663596021414889)
> fix(flyout-menu): ensure div scrolls when setting a max height or width

- collections/forms/src/validators/__tests__/dhis2Username.test.js
- collections/forms/src/validators/dhis2Username.js
Same as with `_`, `@` and `.` , we should allow `-`, but only single ones and not at the username’s start or end.
Some related JIRA issues:
- [DHIS2-13824](https://dhis2.atlassian.net/browse/DHIS2-13824) (current issue)
- [DHIS2-13768](https://dhis2.atlassian.net/browse/DHIS2-13768) (backend, not completely right)
- [DHIS2-13823](https://dhis2.atlassian.net/browse/DHIS2-13823) (backend, additional fix)
> fix(forms): allow usernames to contain single hyphens

- docs/src/css/custom.css
This PR adds a `Roboto` webfont import for the library documentation. Previously, components seemed to be confused by the `Inter` import and were using `Helvetica`. 
I tried importing and using the `ui` `CssReset` to reset the components to the correct font, but that didn't work. Explicitly loading `roboto` works. I'm open to other ideas if this is problematic.
---
---
Before:
After:
> docs: add webfont for components

- collections/ui/API.md
- components/selector-bar/API.md
- components/selector-bar/src/selector-bar-item/features/toggle-children/index.js
- components/selector-bar/src/selector-bar-item/selector-bar-item.js
- components/selector-bar/src/selector-bar/__stories__/keep-org-unit-expanded.js
- components/selector-bar/src/selector-bar/__stories__/with-right-hand-side-content.js
- components/selector-bar/src/selector-bar/__stories__/with-some-inputs.js
- components/selector-bar/src/selector-bar/selector-bar.test.js
Implements [LIBS-371](https://dhis2.atlassian.net/browse/LIBS-371)
---
Allow clearing of single selections from `SelectionBarItem` component.
Add a `displayOnly` SelectionBarItem component
[Figma prototype](https://www.figma.com/proto/9zvqbQKtrWIElNQ8ZYxyha/capture-context-selector?page-id=0%3A1&node-id=3%3A3435&viewport=1740%2C62%2C0.28&scaling=min-zoom&starting-point-node-id=3%3A1134) 
---
---
> feat(selection-bar-item): [LIBS-371] display only and clear selection callback 

- components/menu/src/menu-item/menu-item.js
- components/menu/src/menu-item/menu-item.styles.js
- components/menu/src/menu-section-header/menu-section-header.js
Implements [UX-122](https://dhis2.atlassian.net/browse/UX-122).
---
This PR makes visual style adjustments to the `MenuItem` and `MenuSectionHeader` components. These are minor changes based on seeing the components in use.
---
-   [x] Using a negative margin to pull the `Chevron` further to the right on items with children. Feels like a hack?
---
> fix(menu): adjust visual styles

- components/field/src/field/field.js
- components/help/src/help.js
- components/input/src/input/input.js
- components/label/src/label.js
This PR makes minor adjustments to the `Field`, `Input`, `Help` and `Label` components. The adjustments are styling and placement. The `cursor: help;` hover style was removed from the `Help` component, as this had caused confusion a few times and was not offering useful info.
---
> fix: field-related component styling adjustments

- components/header-bar/src/apps.js
Implements [DHIS2-8651](https://dhis2.atlassian.net/browse/DHIS2-8651)
---
This is a fix to break app names when they have long names (typical in languages like Norwegian)
---
-   no known issues
---
I don't think these are relevant for this ticket?
---
**Before**
**After**
Notes:
- I have used `overflow-wrap: anywhere` rather than `word-break: break-all` (as suggested in the ticket), as `word-break: break-all` would break anywhere (where as `overflow-wrap: anywhere` tries to break at work boundaries):
- I have removed the padding from the anchor and instead put a margin on the img, so that the text can flow to the boundary of the anchor element. I did this to eliminate word breaks looking like they …
> fix: wrap app names

- docs/docs/components/notice-box.md
This PR fixes a documentation example for the `NoticeBox`, which was previously showing the wrong type.
---
> docs: fix noticebox error example

- components/select/src/multi-select/__tests__/selection-list.test.js
- components/select/src/multi-select/selection-list.js
- components/select/src/single-select/__tests__/selection.test.js
- components/select/src/single-select/selection.js
https://dhis2.atlassian.net/browse/LIBS-401
Currently this doesn't show the value in the dropdown, only in the input. That means it can be programmatically selected, but once the selection is removed the user can't select it again through the dropdown. Made the most sense to me since it isn't part of the options, so this way it fails gracefully in production, but doesn't behave too weirdly.
> feat(select): use selection value as a label as fallback in production

- components/organisation-unit-tree/src/organisation-unit-tree/use-root-org-data/use-root-org-data.js
Workaround for silencing the warning about queries not being static.
It was initially suggested by @amcgee and it's used in other places.
---
---
This is the console log in from the storybook org unit example when expanding the root node (before the fix):
> fix(organisation-unit-tree): silence static query warning

- icons/svgr.config.js
- icons/templates/icon-template.js
After running `yarn build`, the generated components now look like this:
```jsx
import PropTypes from 'prop-types'
import * as React from 'react'
function SvgAdd16({ color, dataTest }) {
return (
<svg
height={16}
viewBox="0 0 16 16"
width={16}
xmlns="http://www.w3.org/2000/svg"
color={color}
data-test={dataTest}
>
<path
d="M8 2a1 1 0 011 1v4h4a1 1 0 010 2H9v4a1 1 0 01-2 0V9H3a1 1 0 110-2h4V3a1 1 0 011-1z"
fill="currentColor"
fillRule="evenodd"
/>
</svg>
)
}
SvgAdd16.propTypes = {
color: PropTypes.string,
dataTest: PropTypes.string,
}
export default SvgAdd16
```
> feat: add dataTest prop to icons

- components/input/src/input/input.js
- components/select/src/multi-select/multi-select.stories.js
- components/select/src/select/input-wrapper.js
- components/select/src/single-select/single-select.stories.js
- components/text-area/src/text-area/text-area.styles.js
This PR updates styles for input-type components. Existing styles were inconsistent or buggy. 
Overview of changes:
- `Input` was 1px taller in Firefox at both `regular` and `dense` sizes. I've resorted to `max-height` to fix this, as nothing else worked.
- I can't imagine using `max-height` being problematic because this is always a single line input, but just want to check this is OK?
- `SingleSelect` and `MultiSelect` `dense` sizes changed from `34px` to the correct `32px`.
- Adjusted some `box-shadow`s.
- `Textarea` padding, lineheight updated.
- Added some storybook demos for easier testing.
---
_All points above should be relevant for feature PRs. For bugfixes, some points might not be …
> fix: update input-type component styles

- components/transfer/src/transfer.js
This fixes a catch-22 I'm encountering with the transfer in combination with final-form. The transfer expects `selected` to be an array (i.e. not undefined). I think it would be good to make it more robust and not assume that selected is passed.
To fix the above in an app it's not too much trouble to supply an `initialValue` for a field with final-form, which is what I did initially. The problem is that an initialValue on a final-form field overrides the form's `initialValues` property.
Passing initialValues to a form is how you'd commonly seed a form with values if it's an edit form. So supplying an initialValue to the transfer based field fixes the transfer crashing if selected is not present, but it breaks the initialValues workflow for seeding an entire form with server-side values. …
> fix(transfer): do not assume selected can be mapped

- components/calendar/package.json
Without this dependency, the `yarn setup` command from the project root will fail with the following error message:
```
Module not found: Error: Can't resolve '../locales/index.js' in '/Users/hendrik/Apps/ui/components/calendar/src/calendar-input'
```
> chore(deps): add i18n dependency

- components/table/src/data-table/data-table-cell.js
Relates to [DHIS2-15767](https://dhis2.atlassian.net/browse/DHIS2-15767)
Required by https://github.com/dhis2/line-listing-app/pull/427
---
_Background_
Using a `Tooltip` in a `DataTable` is currently quite tricky, as the table itself relies on a strict DOM structure of `DataTableBody` -> `DataTableRow` -> `DataTableCell`, so nothing else can easily be added into that structure. To wrap a `Tooltip` around an element without any additional side-effect elements the wrapped component (’DataTableCell`) needs to implement a few props, such as ’onMouseOver’, ’onMouseOut’ and ’ref’. Currently the `DataTableCell` doesn't pass through the former two of these.
_Solution_
`DataTableCell` will now pass through `props` to its underlying `TableCell` component, so that the props will be featured in e.g. …
> fix: pass through props for DataTableCell (DHIS2-15767)

- components/pagination/src/pagination.js
- components/pagination/src/pagination.stories.js
Relates to [DHIS2-15465](https://dhis2.atlassian.net/browse/DHIS2-15465)
---
This is a very unobtrusive PR that only adds a `row-gap` CSS rule to the pagination container to prevent the button "rows" touching when the pagination container is narrow. Implementation was discussed with Joe.
---
_NB: API docs and tests weren't relevant for this PR._
---
**BEFORE**
**AFTER**
[DHIS2-15465]: https://dhis2.atlassian.net/browse/DHIS2-15465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(pagination): add row padding on small screens and demo stories

- components/portal/src/portal.js
So far the default mount node was defined directly in the module, not when the portal was rendered. When running jest tests, the portal won't be in the current DOM as the mount node that's supposed to be used has changed.
-   [x] ~~API docs are generated~~
- Not necessary
-   [x] ~~Tests were added~~
- I couldn't reproduce the issue in this repository, the jest test actually passed
-   [x] ~~Storybook demos were added~~
- Not necessary
> fix(portal): get default mount node at execution time

- components/input/types/index.d.ts
- components/organisation-unit-tree/types/index.d.ts
- components/radio/types/index.d.ts
- components/select/types/index.d.ts
- components/transfer/types/index.d.ts
- Make `value` and `name` required in `InputEventPayload` - but keep them being able to be undefined.
- Export more handlers and payloads. Useful to get the type when eg. consuming the components. 
---
---
> fix: minor type fixes

- .github/workflows/dhis2-verify-lib.yml
Update workflow to fix some of the deprecations. Based on https://github.com/dhis2/workflows/blob/master/ci/dhis2-verify-lib.yml
> ci: update publishing workflow

- .github/workflows/dhis2-verify-lib.yml
The workflow updates introduced new issues that require us to fix our peerdeps. We should still not stick around on 14, but this rolls it back just to allow us to fix the broken version on npm.
> fix: rollback to node 14

- components/button/src/button/button.js
- components/button/src/button/button.stories.js
- components/button/src/button/button.styles.js
- constants/src/shared-prop-types.js
- docs/docs/components/button.md
Implements [LIBS-544](https://dhis2.atlassian.net/browse/LIBS-544) / [UX-157](https://dhis2.atlassian.net/browse/UX-157)
---
This PR implements, or allows, buttons that are both `destructive` and `secondary`. `secondary` prop is now used as a modifier rather than a standalone type, as it can be applied to both `basic` and `destructive` types. (Using `secondary` alone is considered a modifier applied to the default `basic` type.) 
In order to allow this, the `secondary` prop is no longer part of the shared prop types provided by UI constants.
Question: is this a breaking change? I believe all button usages are unaffected by this change, but I'm not sure if changing `PropType` definitions always counts as a breaking change.
---
-   [x] …
> feat(button): add destructive, secondary button type

- components/button/src/dropdown-button/dropdown-button.js
- components/button/src/split-button/split-button.js
- constants/src/shared-prop-types.js
Fixes an issue with release of `15.0.0`, where `buttonVariantPropType` was removed, but still referenced in internal components. See https://github.com/dhis2/ui/pull/1424 .
This PR reintroduces the propType (but deprecated) because it's actually part of the public API. 
Fixed the references to this propType, and aligned the documentation of those props with `button`.
> fix(prop-type): fix deprecation of buttonVariantPropType

- components/button/src/dropdown-button/dropdown-button.js
- components/button/src/split-button/split-button.js
- constants/src/shared-prop-types.js
Prepares alpha 9 release. Fixes some bad merge resolutions, and brings back `buttonVariantArgType` that is used for storybook. 
BREAKING CHANGE: `buttonVariantPropType` has been removed from constants. This is mostly intended for internal purposes, but was part of the public API.
> fix(constants): remove buttonVariantProptype from constants

- components/menu/src/menu-item/features/accepts_suffix.feature
- components/menu/src/menu-item/features/accepts_suffix/index.js
- components/menu/src/menu-item/menu-item.js
- components/menu/src/menu-item/menu-item.stories.e2e.js
- components/menu/src/menu-item/menu-item.stories.js
- components/menu/src/menu-item/menu-item.styles.js
- docs/docs/components/menu.md
- docs/src/css/custom.css
Implements [LIBS-536](https://dhis2.atlassian.net/browse/LIBS-536)
---
This PR adds the optional `suffix` prop to `<MenuItem>`. A `suffix` is displayed at the end of the component. A `suffix` can be used alongside `chevron: true`.
---
---
[LIBS-536]: https://dhis2.atlassian.net/browse/LIBS-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: menu item suffix

- components/alert/src/alert-bar/action.js
- components/alert/src/alert-bar/alert-bar.stories.js
Implements [LIBS-253](https://dhis2.atlassian.net/browse/LIBS-253)
---
Long texts caused the action bar's description and action labels to break oddly.
---
-   ~~[ ] API docs are generated~~
- not necessary
-   ~~[ ] Tests were added~~
- not necessary
---
**before:**
**after:**
[LIBS-253]: https://dhis2.atlassian.net/browse/LIBS-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(alertbar): address long texts

- components/table/src/data-table/__tests__/data-table-row.test.js
- components/table/src/data-table/data-table-row/data-table-row.js
- components/table/src/table/table-row.js
Implements [LIBS-539](https://dhis2.atlassian.net/browse/LIBS-539)
---
This forward props down to data-row and table-row components to allow consumers to handle DOM events like click and mouseover. 
---
We have a bigger initiative to allow passing down props for most of our UI components. This was more urgent since it's blocking analytics team, and what we need to pass down made sense. Some components that encapsulate more than one native component might be trickier to implement.
The typings for this should be updated (to inherit from `HTMLTableRowElement`) but I had issues with running types inside the project, which we need to talk about separately.
---
-   [] API docs are generated
[LIBS-539]: …
> feat(LIBS-539): forward data-table-row props to allow handling dom events

- components/segmented-control/src/segmented-control.js
- components/segmented-control/src/segmented-control.stories.js
Implements [LIBS-568](https://dhis2.atlassian.net/browse/LIBS-568) and [UX-160](https://dhis2.atlassian.net/browse/UX-160)
---
This PR improves accessibility and adjusts the design of the `SegmentedControl` component.
---
Before:
After:
[LIBS-568]: https://dhis2.atlassian.net/browse/LIBS-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UX-160]: https://dhis2.atlassian.net/browse/UX-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(segmented-control): adjust design and accessibility

- components/chip/src/chip.js
- components/menu/src/menu-item/menu-item.stories.js
- components/menu/src/menu-item/menu-item.styles.js
- components/pagination/src/page-controls.js
- components/sharing-dialog/src/sharing-dialog.stories.js
- components/transfer/src/icons.js
This PR makes fixes suggsted by @KaiVandivier in PR review for merge from alpha to main: https://github.com/dhis2/ui/pull/1452
> fix: clean up from pr review

- components/loader/src/circular-loader/__tests__/circular-loader.test.js
- components/loader/src/circular-loader/circular-loader.js
- components/loader/src/circular-loader/circular-loader.stories.js
- components/loader/src/linear-loader/__tests__/linear-loader.test.js
- components/loader/src/linear-loader/linear-loader.js
- components/loader/src/linear-loader/linear-loader.stories.js
- components/loader/types/index.d.ts
Implements [560](https://dhis2.atlassian.net/browse/LIBS-560)
---
This feature improves the accessibility of the loaders by adding aria attributes to them, i.e.
- the `aria-valuenow` and `aria-label` attributes to the linear loader
- the `aria-label` attribute to the circular loader
---
> feat: add aria attributes to loaders

- components/select/package.json
- components/select/src/multi-select-field/features/has_default_clear_text.feature
- components/select/src/multi-select-field/features/has_default_clear_text/index.js
- components/select/src/multi-select/input.js
- components/select/src/select/input-clear-button.js
- components/select/src/single-select-field/features/has_default_clear_text.feature
- components/select/src/single-select-field/features/has_default_clear_text/index.js
- components/select/src/single-select/input.js
Implements [UX-154](https://dhis2.atlassian.net/browse/UX-154)
---
This PR changes the `SingleSelect` and `MultiSelect` clear button to use an icon button rather than a `Button` with text label.
`clearText` prop is used to populate the `Tooltip` that appears on hover.
---
---
Before: 
After:
[UX-154]: https://dhis2.atlassian.net/browse/UX-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(select): adjust clear button

- components/tooltip/src/tooltip.js
- components/tooltip/src/tooltip.test.js
Implements [LIBS-558](https://dhis2.atlassian.net/browse/LIBS-558)
---
---
-   Tooltip can't be hovered when `closeDelay` is set to `zero`.
---
[LIBS-558]: https://dhis2.atlassian.net/browse/LIBS-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tooltip): accessibility improvements for tooltip

- docs/docs/components/alertbar.md
- docs/docs/components/avatar.md
- docs/docs/components/button.md
- docs/docs/components/calendar.md
- docs/docs/components/card.md
- docs/docs/components/checkbox.md
- docs/docs/components/chip.md
- docs/docs/components/data-table.md
- docs/docs/components/fileinput.md
- docs/docs/components/inputfield.md
- docs/docs/components/loading.md
- docs/docs/components/menu.md
- docs/docs/components/modal.md
- docs/docs/components/notice-box.md
- docs/docs/components/org-unit-tree.md
- docs/docs/components/pagination.md
- docs/docs/components/popover.md
- docs/docs/components/radio.md
- docs/docs/components/segmented-control.md
- docs/docs/components/select.md
- docs/docs/components/switch.md
- docs/docs/components/tab.md
- docs/docs/components/tag.md
- docs/docs/components/tooltip.md
- docs/docs/components/transfer.md
The current demo links were fixed to be in the `/demo` format, however, Docusaurus hijacks the links and tries to look up the path internally even though the URL was correct. This new format restores the functionality also back to  how it was originally, demo opening in a new tab.
> docs: fix relative demo links to open in new tab

- components/button/types/index.d.ts
I don't think we should extend `HTML`-elements directly. In some cases like `tabIndex` we're actually using a conflicting type, which causes type-errors in our types. 
`tabIndex` should really be a `number` (that's what the html type is), but that would be breaking due to our prop-types etc.
So instead of ButtonProps extending the `HTMLButtonElement`, I'm using type intersection with the `ComponentPropsWithoutRef<'button'>` without the keys for `ButtonProps`, to avoid conflicts. 
I also split this in two types types because eg. `export interface ButtonProps extends Omit<React.ComponentPropsWithoutRef<'button'>, keyof ButtonProps>`) wouldn't work because of circular references. 
See https://github.com/typescript-cheatsheets/react/blob/main/docs/advanced/patterns_by_usecase.md#wrappingmirror …
> fix(button): fix prop types for button

- components/button/src/dropdown-button/__tests__/dropdown-button.test.js
- components/button/src/dropdown-button/dropdown-button.js
Implements [LIBS-561](https://dhis2.atlassian.net/browse/LIBS-561)
---
Implemented [LIBS-561](https://dhis2.atlassian.net/browse/LIBS-561) by updating the drowpdownButton component to close on click of the escape button. 
---
-   [ ] None
[LIBS-561]: https://dhis2.atlassian.net/browse/LIBS-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIBS-561]: https://dhis2.atlassian.net/browse/LIBS-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: accessibility on dropdown button

- components/button/src/button/__tests__/Button.test.js
- components/button/src/button/button.js
- components/button/src/split-button/split-button.js
- components/button/src/split-button/split-button.test.js
- components/loader/src/circular-loader/__tests__/circular-loader.test.js
- components/loader/src/circular-loader/circular-loader.js
- components/loader/src/circular-loader/circular-loader.stories.js
- components/loader/src/linear-loader/__tests__/linear-loader.test.js
- components/loader/src/linear-loader/linear-loader.js
- components/loader/src/linear-loader/linear-loader.stories.js
- components/loader/types/index.d.ts
- components/tooltip/src/tooltip.js
- components/tooltip/src/tooltip.test.js
This is a cherry-pick for features already in `alpha` branch. Fixes:
- Button accessibility: https://dhis2.atlassian.net/browse/LIBS-565 
- Loaders accessiblity: https://dhis2.atlassian.net/browse/LIBS-560
- Tooltip accessibility: https://dhis2.atlassian.net/browse/LIBS-558
- Split button accessibility: https://dhis2.atlassian.net/browse/LIBS-566
> feat: accessibility updates from alpha

- components/switch/src/switch/__tests__/switch.test.js
- components/switch/src/switch/switch.js
- components/switch/types/index.d.ts
Implements [LIBS-572](https://dhis2.atlassian.net/browse/LIBS-572)
---
This feature improves the accessibility of the `Switch` component by adding an optional aria-label attribute
---
-   [x] _issue_
---
---
[LIBS-572]: https://dhis2.atlassian.net/browse/LIBS-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(switch): accessibility improvements for the switch component

- components/button/src/split-button/split-button.js
Fixes an issue where the split button swallows the key down event regardless of wheteher it's ESC being hit or not
---
> fix(split-button): stop swallowing key down events

- components/menu/types/index.d.ts
- components/modal/src/modal-title/modal-title.js
- components/modal/types/index.d.ts
- components/tag/src/tag.js
- components/tag/types/index.d.ts
- icons/types/index.d.ts
While moving the instance manager FE from CRA to Vite, I encountered some type issues in this repository, see commit messages:
* fix(icon types): export IconSubtract16 & IconSubtract24
* fix(menu item types): make suffix prop optional
* fix(modal types): accept ReactNodes as children
* fix(tag types): accept ReactNodes as children
> fix(ts and prop types): correct some types and propTypes

- components/calendar/src/calendar-input/calendar-input.js
- components/calendar/src/calendar/calendar-container.js
- components/calendar/src/calendar/calendar-table.js
- components/calendar/src/calendar/calendar.js
- components/calendar/src/calendar/navigation-container.js
Implements [LIBS-440](https://dhis2.atlassian.net/browse/LIBS-440)
Some minor performance improvements for multi-calendar component:
- use calendar inner components directly to avoid double calls to multi-calendar library.
-  revert `Calendar` component to its old state, since it doesn't need to handle two states (when used independently, and when used as part of `CalendarInput`)
- use validation, error, and warning directly from the hook rather than wrapping them in an effect
Additionally, I've tried to change the component to being semi-controlled, so it doesn't call the hook multiple times unnecessary, and only when leaving the input. This worked in improving the performance (screenshots attached), but overcomplicated the interaction with the inner `calendar`. After several attempts, I …
> refactor: improve performance of calendar component

- components/menu/src/flyout-menu/__tests__/flyout-menu.test.js
- components/menu/src/flyout-menu/flyout-menu.js
- components/menu/src/flyout-menu/flyout-menu.stories.js
- components/menu/src/menu-item/menu-item.js
- components/menu/src/menu/use-menu.js
- components/menu/types/index.d.ts
- components/popper/src/popper.js
Implements [LIBS-563](https://dhis2.atlassian.net/browse/LIBS-563)
---
This feature improves the accessibility of the flyout menu component
- A user can close the flyout menu by pressing the `Escape` key
- By pressing the `Right Arrow` key on a focused menu item containing a submenu, a flyout menu is opened and focus is placed on the 1st item.
- By pressing the `Left Arrow` key on any focused item inside a submenu, it will close and focus the parent menu item  if any. 
---
---
[LIBS-556]: …
> feat(flyout-menu): accessibility improvements for flyout menu component

- package.json
- yarn.lock
attempts to fix the release step in master - The error we get now is [EINVALIDTAGNAME](https://github.com/dhis2/ui/actions/runs/10249760523/job/28355082754#step:7:1136) which seems like it would be fixed by using `--legacy-peer-deps` flag again (according to [this](https://stackoverflow.com/a/67301099) and other places), but trying to solve it without doing that.
The error happens in the [prepare step ](https://github.com/dhis2/action-semantic-release/blob/f72ea64f5c6215abf3aca5e9c908fd7b62cc6c3a/dist/index.js#L22927-L22928) of our semantic-release version when it runs [npm version](https://github.com/semantic-release/npm/blob/master/lib/prepare.js#L15). It is likely due to the action using node 12 (npm < 7) which has a different [behaviour](https://stackoverflow.com/a/66620869) when it …
> fix: pin react version in resolution

- components/select/src/select/menu-wrapper.js
- components/select/src/single-select-field/features/can_show_conditionally.feature
- components/select/src/single-select-field/features/can_show_conditionally/index.js
- components/select/src/single-select-field/single-select-field.e2e.stories.js
Fixes https://dhis2.atlassian.net/browse/LIBS-532
This fix involves disabling portal for the Select Menu Wrapper. 
I looked mainly at ensuring the ref is updated before when the parent is show, by using a callback ref (similar to [this](https://react.dev/reference/react-dom/components/common#ref-callback) and [this](https://legacy.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)). But there were complications, the first is that this technique works only with functional componet, I tried the class-based version of it but that didn't work. I tried converting the component into a functional one, and quickly got into a rabbit hole.
https://github.com/dhis2/ui/assets/1014725/e9d75595-015d-4a20-83c6-6352294da4d1
> fix: select-field not showing in correct place

- docs/docs/utilities/constants.md
This removes the `(not recommended)` parenthetical about using <CssVariables> component for making DHIS2 UI constants accessible in CSS.
Summary of points from slack conversation where we discussed why we originally had this language:
- ...the original rationale behind that was that these constants are used in the design system and that apps are made using the design system so they should not be needed. (Hendrik)
- Maybe there was a time when we were using css-in-js styles that could consume the constants from the UI library? (Kai)
In summary, we now recognize that it is common to need these values (e.g. colors) for styling and that as we mostly use css modules for styling, it makes sense to not officially discourage use of <CSSVariables> component.
> chore: update css variables info

- components/input/src/input-field/input-field.js
Building with Vite/Rollup reveals a warning about a circular dependency:
```sh
Export "InputField" of module "node_modules/@dhis2-ui/input/build/es/input-field/input-field.js" was reexported through module "node_modules/@dhis2-ui/input/build/es/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
```
In my tests in apps, other components like `MenuItem` and `SingleSelectField` also created warnings, but those ones have [already](https://github.com/dhis2/ui/commit/83b611a721881f5913642b7e103181f923ebc697) been …
> fix: circular dependency in input-field

- components/calendar/package.json
- components/calendar/src/calendar-input/calendar-input.js
- components/calendar/src/calendar/calendar-table-cell.js
- components/calendar/src/calendar/calendar-table.js
- components/calendar/src/calendar/calendar.js
- components/calendar/types/index.d.ts
- yarn.lock
BREAKING CHANGE: multi-calendar hook no longer returns Temporal date - although it's unlikely to affect anyone, it's a breaking change in theory and should be reflected as such.
more context here: https://github.com/dhis2/multi-calendar-dates/pull/75
Implements [DHIS2-18131](https://dhis2.atlassian.net/browse/DHIS2-18131)
[DHIS2-18131]: https://dhis2.atlassian.net/browse/DHIS2-18131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump multi-calendar library

- components/calendar/types/index.d.ts
---
Fixes some minor type issues when working the `CalendarInput`. 
* Allow "label" to be passed
This was previously omitted from types, but we are in fact spreading it as part of rest to input field - which is great.
* Add "clearable" property.
This was missing in types but is documented in storybook and ui docs.
> fix(calendar): fix minor type issues

- components/sharing-dialog/types/index.d.ts
`route` also is supported by sharing API, and currently gives a type error.
> fix(sharing-dialog): add 'route' to SharingType type

- components/input/src/input-field/input-field.js
- components/input/src/input-field/input-field.prod.stories.js
- components/input/src/input/input.js
- components/input/types/index.d.ts
Implements [LIBS-699](https://dhis2.atlassian.net/browse/LIBS-699)
[LIBS-699]: https://dhis2.atlassian.net/browse/LIBS-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: make input field clearable and add prefix icon

- components/tooltip/src/tooltip.js
> fix: remove redundant wrapper object from onfocus and onblur callbacks

- components/menu/src/menu-item/__tests__/menu-item.test.js
- components/menu/src/menu-item/menu-item.js
Implements [LIBS-715](https://dhis2.atlassian.net/browse/LIBS-715)
---
If `label` is not a string, the `aria-label` attribute ends up as `[object Object]`. An `ariaLabel` prop on the `MenuItem` is added to provide a better value for `aria-label` in that case
---
-   [X] API docs are generated
-   [X] Tests were added
-   [ ] ~Storybook demos were added~
[LIBS-715]: https://dhis2.atlassian.net/browse/LIBS-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(menu-item): add ariaLabel prop to use if label prop is not a string

- components/menu/src/menu-item/menu-item.js
- components/menu/src/menu-item/menu-item.prod.stories.js
- components/menu/src/menu-item/menu-item.styles.js
This PR contains two loosely related changes:
Setting the active class on items with tab index 0 works nicely when using keyboard navigation but causes odd behaviour when using mouse-based interaction: a `Menu` with `MenuItems` can end up having multiple "active items":
By removing this code the keyboard navigation is still visually supported by the focus outline, which is enough IMO.
The problem was as follows:
* The menu-item styles included focus styles for the `<a>` tag
* This makes sense because these are "naturally focusable elements", similar to a button.
* However now that we have keyboard navigation, the parent `<li>` gets a `tab-index` and the `<li>` becomes the element that receives focus
So I've moved the focus styles from the `<a>` to the `<li>` and everything looks better. …
> fix(menu-item): tweak active and focused styles

- components/select/src/select/input-wrapper.js
This PR prevents a prop-types error by making `tabIndex` an optional prop, which is not a problem since `tabIndex` also [has a default value](https://github.com/dhis2/ui/blob/9459c0678931a13d8b3450bd2fcc97005eb3cca5/components/select/src/select/input-wrapper.js#L11) in the component.
I originally encountered this bug in the sharing dialog-after upgrading `@dhis2/ui` in the Dashboards App and was able to reproduce it bug in the "For dashboard with cascading sharing partial success" demo story. I have also been able to verify that this PR addresses the issue this way.
> fix(select): prevent prop-types error by making `tabIndex` an optional prop

- components/calendar/types/index.d.ts
simple type fix for calendar input
> fix: add format to calendar input props

- components/input/types/index.d.ts
---
This PR: LIBS-699/clearable-input-and-prefix-icon added `width` as a prop, but forgot to add it to the types.
> fix(types): fix missing width type for input

- components/selector-bar/package.json
Noticed this when examining testing-library deps in the app platform alpha:
It shouldn't be necessary here; there's a dev dependency at the package root
> fix(deps): remove testing-library from selector bar prod deps

- components/header-bar/src/command-palette/__tests__/browse-apps-view.test.js
- components/header-bar/src/command-palette/__tests__/browse-commands-view.test.js
- components/header-bar/src/command-palette/__tests__/browse-shortcuts-view.test.js
- components/header-bar/src/command-palette/__tests__/command-palette.test.js
- components/header-bar/src/command-palette/__tests__/home-view.test.js
- components/header-bar/src/command-palette/__tests__/search-results.test.js
- components/header-bar/src/command-palette/hooks/use-navigation.js
- This PR fixes the failing tests related to the command palette after the React 18 upgrade. By using the fireEvent API (instead of the originally used userEvent API) to simulate keyboard events, i.e. pressing `Ctrl/Meta` + `/`, to simulate the opening and closing of the command palette modal.
> test: fix failing command palette tests

- components/transfer/src/filter.js
- components/transfer/src/options-container.js
- components/transfer/src/transfer-option.js
Implements [LIBS-728](https://dhis2.atlassian.net/browse/LIBS-728)
---
This PR makes two minor style changes to `Transfer`:
- Use `dense` inputs for the default filter inputs
- Apply margin to first and last options, rather than the options container, which removes the spacing above/below the scrollbar.
---
---
Before 1: 
After 1:
Before 2:
After 2:
[LIBS-728]: https://dhis2.atlassian.net/browse/LIBS-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(transfer): adjust filter inputs and container spacing [LIBS-728] 

- .github/workflows/generate-and-upload-bom.yml
Implements [SEC-60](https://dhis2.atlassian.net/browse/SEC-60)
---
1. Integration of Static Analysis Security Scanning Tool: Dependency Track: https://dtrack.security.dhis2.org/projects
2. Running every night so it won't bother Developers 
---
Dependency Track will scan the created SBOM and analyze for CVEs and open vulnerabilities.
Those reports will be evaluated by the security team and will be brought back to the dev teams if something crucial pops up
---
[SEC-60]: https://dhis2.atlassian.net/browse/SEC-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add workflow for dependency-track

- components/sharing-dialog/src/constants.js
Implements [DHIS2-19007](https://dhis2.atlassian.net/browse/DHIS2-19007)
---
This PR adds the `dataStore` resource to the list of accepted types for the Sharing Dialog component. This is to support the [sharing feature](https://github.com/dhis2/datastore-app/pull/145) in the new DataStore app. 
---
----
[DHIS2-19007]: https://dhis2.atlassian.net/browse/DHIS2-19007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add dataStore to SharingDialog types

- components/header-bar/src/command-palette/__tests__/browse-apps-view.test.js
- components/header-bar/src/command-palette/__tests__/search-results.test.js
- components/header-bar/src/command-palette/context/command-palette-context.js
- components/header-bar/src/command-palette/hooks/use-navigation.js
- components/header-bar/src/command-palette/views/home-view.js
- components/header-bar/src/command-palette/views/list-view.js
Fixes [LIBS-756](https://dhis2.atlassian.net/browse/LIBS-756)
----
This PR fixes some highlighting issues after the search filter has been cleared. 
1. It highlights first category item in the category view instead of the `back action`
2. It highlights the first item in the default section in the home view
---
Before:
https://github.com/user-attachments/assets/febafd54-7a42-44ea-b437-ba4d693e16ab
After:
https://github.com/user-attachments/assets/5c6d2a90-046c-4219-b7f2-60e15b7d28b5
[LIBS-756]: https://dhis2.atlassian.net/browse/LIBS-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(command-palette): highlighting after search mode

- components/header-bar/src/command-palette/__tests__/search-results.test.js
- components/header-bar/src/command-palette/hooks/use-actions.js
- components/header-bar/src/command-palette/sections/list.js
Implements [LIBS-755](https://dhis2.atlassian.net/browse/LIBS-755)
---
This PR makes the action items on the home view searchable, i.e `Browse Apps`, `Browse Commands`, and `Browse Shortcuts`
---
---
https://github.com/user-attachments/assets/bba998ec-7278-4031-a17f-e738fdad9fd0
[LIBS-755]: https://dhis2.atlassian.net/browse/LIBS-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(command-palette): searchable category actions

- components/sharing-dialog/src/sharing-dialog.js
- components/sharing-dialog/src/sharing-dialog.prod.stories.js
- components/sharing-dialog/src/tabs/tabbed-content.js
- components/sharing-dialog/types/index.d.ts
Please see this Slack thread for details https://dhis2.slack.com/archives/C07A1DURSUA/p1740488506323349
> feat: allow sharing embedded dashboards

- components/select/src/multi-select-option/multi-select-option.js
- components/select/src/single-select-option/single-select-option.js
Implements [UX-178](https://dhis2.atlassian.net/browse/UX-178)
---
This PR adjusts the `active` style for `SingleSelect` options to improve readability and better align with native browser `select` styles. Minor cosmetic changes to the `MultiSelect` `active` option are included for consistency.
---
---
Before (`SingleSelect`): 
After (`SingleSelect`):
Before (`MultiSelect`):
After (`MultiSelect`):
`SingleSelect` option handling multiline content:
[UX-178]: https://dhis2.atlassian.net/browse/UX-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> fix(select): adjust active option style

- components/select/src/select/input-clear-button.js
- components/select/src/select/input-wrapper.js
This PR makes minor changes to the `select` component:
- Adjusts padding and spacing of the end-aligned components (down-arrow and clear action)
- Prevents clear button icon shrinking
---
---
Before:
After:
> fix(select): adjust spacing, padding, clear icon

- components/button/src/dropdown-button/dropdown-button.js
Fixes [UX-188](https://dhis2.atlassian.net/browse/UX-188)
---
This PR adjusts the spacing of the `DropdownButton` arrow icon.
---
---
Before:
After:
[UX-188]: https://dhis2.atlassian.net/browse/UX-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(button): adjust dropdown arrow spacing for small buttons

- components/calendar/src/calendar-input/calendar-input.js
- components/calendar/src/calendar/calendar-container.js
- components/menu/src/flyout-menu/flyout-menu.js
- components/popover/src/popover.js
- components/popover/src/popover.prod.stories.js
- components/select/src/select/menu-wrapper.js
- constants/src/elevations.js
Implements [UX-189](https://dhis2.atlassian.net/issues/UX-189?filter=11797)
---
This PR introduces a `popover` `elevation` constant, using it in all situations where a consistent style should be used. (This is a small step in the direction of [design tokens](https://dhis2.atlassian.net/browse/UX-119)).
---
---
[UX-189]: https://dhis2.atlassian.net/browse/UX-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: popover elevation [UX-189]

- .github/workflows/dhis2-preview-pr.yml
- .github/workflows/dhis2-verify-commits.yml
- .github/workflows/dhis2-verify-lib.yml
Replaces the [deprecated gha-yarn-cache](https://github.com/c-hive/gha-yarn-cache?tab=readme-ov-file#deprecated):
> This functionality is now part of [actions/setup-node](https://github.com/actions/setup-node):
```
- name: Setup Node.js
uses: actions/setup-node@v3
with:
node-version: '16'
cache: 'yarn'
```
> ci: update yarn cache method

- components/calendar/package.json
- yarn.lock
bumps to the latest version of multi-calendar-dates (mainly for the [fix](https://github.com/dhis2/multi-calendar-dates/commit/6f896c6296e23710f744d1a392540df70875bb4b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R75) the declared peer dependency)
> fix: bump multi-calendar-dates

- .github/workflows/dhis2-deploy-netlify.yml
- .github/workflows/dhis2-verify-lib.yml
This PR:
- ensures that the updated docs are published
- sends a slack notification when master branch publishes (or fails to publish) a new version
> fix: ensure publishing docs

- components/calendar/src/calendar-input/calendar-input.js
- components/calendar/src/calendar/calendar-container.js
Implements [LIBS-718](https://dhis2.atlassian.net/browse/LIBS-718)
---
In Safari, the [relatedTarget](https://github.com/dhis2/ui/blob/master/components/calendar/src/calendar-input/calendar-input.js#L104) of the blur event resolves to the popper element, whereas in other browsers it points to the clicked element within the calendar. As a result, this [if](https://github.com/dhis2/ui/blob/master/components/calendar/src/calendar-input/calendar-input.js#L104) resolves to false in Safari, causing the calendar to close before the onClick event can be triggered. 
The proposed solution involves storing a reference to the popper in the calendar-input and comparing it with the `relatedTarget`. Since I’m not very familiar with the UI library, any feedback or suggestions for a better approach would …
> fix: [LIBS-718] calendar input onBlur in Safari

- components/transfer/src/transfer.js
The component accepts every number for maxSelections, so changing the prototype accordingly to avoid false warnings
> fix: small fix in transfer proptype

- icons/types/index.d.ts
Implements [JIRA_ISSUE_ID](https://dhis2.atlassian.net/browse/JIRA_ISSUE_ID)
---
This PR adds missing exports for a bunch of icons which prevented them from being used in typescript projects.
---
---
Error about missing export shown in the editor:
> fix(icons): add missing exports for icon types

- icons/API.md
- icons/src/svg/dimension-program-attribute-16.svg
- icons/types/index.d.ts
Implements [JIRA_ISSUE_ID](https://dhis2.atlassian.net/browse/JIRA_ISSUE_ID)
---
Adding the programattribute icon size 16, which has been located in the Line-listing app. It should be co-located with the other dimension icons in the ui library.
---
---
> feat: add program attribute icon size 16

- components/pagination/types/index.d.ts
- components/table/types/index.d.ts
I encountered some type mismatches between the prop-types and the type definitions. Quite likely this was to do with the usage of the `requiredIf` prop-type helper.
I've added a comment to each type-definition change with a reference to the prop-type it belongs to.
> fix: adjust type definitions to align with prop-types
