dhis2/ui

packages/forms/package.json, yarn.lock
=> fix: update final-form to fix setstate warning

cypress/integration/forms/RadioControl/can_set_a_value.feature, cypress/integration/forms/RadioControl/can_set_a_value/index.js, cypress/integration/forms/RadioControl/common/index.js, cypress/integration/forms/RadioControl/displays_error.feature, cypress/integration/forms/RadioControl/displays_error/index.js, packages/forms/src/RadioControl/RadioControl.stories.e2e.js
The two tests I touched succeed locally.
=> test(radio): refactor test wording to be more explicit

packages/core/src/Field/Field.js
Definitely in my top 3 of smallest PRs so far.
=> fix(field): fix prop-type warning

packages/ui/src/index.js
Export ui-constants from ui as well.
=> feat(constants): export constants as well

cypress/fixtures/HeaderBar/applicationTitle.json, cypress/fixtures/HeaderBar/getModules.json, cypress/fixtures/HeaderBar/getModulesWithSpecialChars.json, cypress/fixtures/HeaderBar/systemInfo.json, cypress/integration/HeaderBar/common/index.js, cypress/integration/HeaderBar/the_headerbar_contains_a_menu_to_all_apps/the_user_will_be_offered_a_menu_with_5_apps.js, cypress/integration/HeaderBar/the_headerbar_should_contain_a_logo_that_links_to_the_homepage/headerbar_contains_logo.js, cypress/integration/HeaderBar/the_headerbar_should_display_the_title_provided_by_the_backend_and_the_app/the_headerbar_displays_the_custom_title.js, cypress/integration/HeaderBar/the_search_should_escape_regexp_character.feature, cypress/integration/HeaderBar/the_search_should_escape_regexp_character/common.js, cypress/integration/HeaderBar/the_search_should_escape_regexp_character/the_modules_do_not_contain_items_with_special_chars.js, cypress/integration/HeaderBar/the_search_should_escape_regexp_character/the_user_searches_for_an_app_with_a_regex_character.js, packages/widgets/src/HeaderBar/Apps.js, packages/widgets/src/HeaderBar/HeaderBar.js, packages/widgets/src/HeaderBar/HeaderBar.stories.e2e.js, packages/widgets/src/HeaderBar/HeaderBar.stories.js, packages/widgets/src/HeaderBar/Logo.js, packages/widgets/src/HeaderBar/Notifications.js, packages/widgets/src/HeaderBar/Profile.js, packages/widgets/src/HeaderBar/Profile/ProfileHeader.js, packages/widgets/src/HeaderBar/Profile/ProfileMenu.js, packages/widgets/src/HeaderBar/joinPath.js
Contains the changes of the two following commits in the [`ui-widgets`](https://github.com/dhis2/ui-widgets/commits/master) repository:
* fix: escape regex special chars in search
* fix: correctly select and use user locale and application title text
=> Upstream changes widgets

packages/widgets/CHANGELOG.md
See here: https://github.com/dhis2/ui-widgets/blob/master/CHANGELOG.md
=> docs(widgets): fix changelog manually

.github/workflows/node-publish.yml
Also use the new org secrets, instead of the local repository ones
=> chore: fix publish action, use dhis2-bot credentials

.github/workflows/cypress.yml, cypress.json, package.json, storybook/package.json, yarn.lock
I should have updated these before merging https://github.com/dhis2/ui/pull/114.
Closes #123
=> test(cypress): update cypress commands

.github/workflows/cypress.yml
=> ci(cypress): increase timeout

docs/getting-started.md
👋 Hey all, this is related to https://github.com/dhis2/ui/issues/119
Simply updates the installation guide to the `@dhis2/ui`
=> docs(getting-started): updates the getting started page with yarn add @dhis2/ui

cypress/integration/Box/accepts_multiple_props.feature, cypress/integration/Box/accepts_multiple_props/index.js, packages/core/src/Box/Box.js, packages/core/src/Box/Box.stories.e2e.js
I noticed that the box isn't applying multiple props. Single props (just marginTop, or maxWidth) are applied correctly, but if you pass multiple props they aren't applied at all. This adds a (currently failing) test that demonstrates the problem.
=> test(box): add test for multiple props

packages/widgets/src/SwitchField/SwitchField.js
Fixes an incorrect prop-type for the SwitchField.
=> fix(switchfield): use correct prop-type for value prop

storybook/.storybook/preview.js
=> docs(storybook): sort components alphabetically

packages/core/src/Button/Button.js, packages/core/src/Button/__tests__/Button.test.js, packages/core/src/ButtonBase/ButtonBase.js, packages/core/src/ButtonBase/__tests__/ButtonBase.test.js
=> refactor(button): render data-test attribute only on button

packages/core/src/IntersectionDetector/IntersectionDetector.js, packages/core/src/IntersectionDetector/IntersectionDetector.stories.e2e.js, packages/core/src/IntersectionDetector/IntersectionDetector.stories.js, packages/core/src/IntersectionDetector/features/Visibility_notification.feature, packages/core/src/IntersectionDetector/features/Visibility_notification/index.js, packages/core/src/index.js
Relates to [TECH-378](https://jira.dhis2.org/browse/TECH-378)
This will add a component that can be used to track whether it's inside the viewport.
=> feat(intersection detector): add component (TECH-378)

d2.config.js, packages/constants/d2.config.js, packages/core/d2.config.js, packages/icons/d2.config.js, packages/ui/d2.config.js
hey 👋  This is related to https://github.com/dhis2/ui/issues/119
I need some guidance @ismay since I dont know how to test this. Is very unlikely this works since I haven't really tested it.
=> fix: removes unused docsite artifacts

packages/widgets/src/Transfer/OptionsContainer.js, packages/widgets/src/Transfer/Transfer.js, packages/widgets/src/Transfer/__tests__/Transfer.test.js
Fixed #247 
When adding the last couple of features, I've refactored the code and a bug snack in.
I've covered the functionality with a test so this particular bug should never appear again.
=> fix(transfer): pass correct selected value to renderOption

packages/core/src/Radio/Radio.js, packages/core/src/Radio/Radio.stories.js
=> fix(radio): no margin if no label

packages/core/src/CenteredContent/CenteredContent.js, packages/core/src/Modal/Modal.js
=> refactor: use different styles for centering CenteredContent/Modal

packages/core/src/Checkbox/Checkbox.js
See #231.
Exactly the same issue here.
=> fix(checkbox): jumping when clicking checkbox

packages/core/src/SplitButton/SplitButton.js, packages/core/src/SplitButton/SplitButton.stories.js, packages/core/src/SplitButton/features/accepts_icon.feature, packages/core/src/SplitButton/features/accepts_icon/index.js
=> fix(split-button): stop showing icon in right button

packages/constants/package.json, packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/ui/package.json, packages/widgets/package.json
Our repo urls in package.json were incorrect. Changed them to the new location.
=> chore(package.json): fix repository urls

CONTRIBUTING.md
Closes https://jira.dhis2.org/browse/LIBS-92
=> docs(contributing): add merge instructions

packages/widgets/src/HeaderBar/TextIcon.js, packages/widgets/src/HeaderBar/TextIcon.test.js
Closes https://jira.dhis2.org/browse/LIBS-49
=> fix(headerbar): use <div> instead of <p> for user avatar initials

packages/widgets/src/HeaderBar/HeaderBar.js, packages/widgets/src/HeaderBar/Profile.js, packages/widgets/src/HeaderBar/features/common/index.js, packages/widgets/src/HeaderBar/features/the_headerbar_conditionally_renders_notification_icons/the_headerbar_conditionally_renders_notification_icons.js
Closes https://jira.dhis2.org/browse/LIBS-73
=> fix(headerbar): specify HeaderBar /api/me query fields required

packages/core/src/Tab/Tab.js
Closes https://jira.dhis2.org/browse/LIBS-77
=> fix: add outline to tab component when focused

packages/core/src/Input/Input.js
Adds a role attribute to the input component.
=> feat(input): add role attribute for input component

packages/core/src/IntersectionDetector/IntersectionDetector.js, packages/core/src/IntersectionDetector/IntersectionDetector.stories.js
Intersection observer stories were broken and throwing a 'rootRef is undefined' error; I'm coming back around to fix it after adding the other changes to storybook.
Also added some description to the IntersectionDetector component and its props.
=> docs: fix intersection observer stories (LIBS-137)

.storybook/main.js
Adds support for MDX story files in the main UI packages
[[LIBS-141]](https://jira.dhis2.org/browse/LIBS-141)
=> chore: load mdx stories in UI packages

packages/core/src/Table/TableCell/TableCell.styles.js, packages/core/src/Table/TableRow/ExpandedRowContent.styles.js, packages/core/src/Table/TableRow/TableRow.styles.js
This PR adjusts the styles for the incoming data table component.
=> fix: data table styles

packages/widgets/src/HeaderBar/Apps.js
This PR is a cherry pick of commit https://github.com/dhis2/ui/pull/473/commits/c9ba64da8c4fd98aa25b380d0525b4f39f08a1c2 from https://github.com/dhis2/ui/pull/473.
The other changes in https://github.com/dhis2/ui/pull/473 are no longer required thanks to some backend fixes.
=> refactor(headerbar): convert Apps to functional component

packages/widgets/src/DataTable/TableElements/Table.stories.internal.js
I have verified locally that this does fix things
=> fix(table): exclude data-table internal table elements stories

packages/core/src/Tag/Tag.js, packages/core/src/Tag/Tag.stories.e2e.js, packages/core/src/Tag/Tag.stories.js, packages/core/src/Tag/features/accepts_max_width.feature, packages/core/src/Tag/features/accepts_max_width/index.js
Fixes LIBS-172
([link](https://jira.dhis2.org/browse/LIBS-172))
=> feat(tag): add maxWidth prop

.github/workflows/dhis2-preview-pr.yml
Added with the new feature in: https://github.com/dhis2/cli-style/pull/408
```sh
yarn d2-style add github workflow-preview-pr
```
That pulls this and installs it to the project: https://github.com/dhis2/workflows/blob/master/ci/dhis2-preview-pr.yml
=> ci(preview): add pr preview workflow

packages/core/src/MenuItem/MenuItem.js
Closes https://jira.dhis2.org/browse/LIBS-191
=> fix(menu-item): do not call event.preventDefault() in onClick handler if href prop is set and user is holding meta/alt/ctrl/shift key

components/pagination/src/pagination.js
See https://github.com/dhis2/notes/discussions/295
=> fix(pagination): make onPageChange and onPageSizeChange optional

components/tag/src/tag-icon.js, components/tag/src/tag.js, components/tag/src/tag.stories.js
Closes https://jira.dhis2.org/browse/LIBS-198
=> fix(tag): support 16px icons

jest.config.js
Folder has been flattened in [b98389c56f1cbfd5cc4b0b5962269ffddabe0cef](https://github.com/dhis2/ui/commit/b98389c56f1cbfd5cc4b0b5962269ffddabe0cef)
and therefore does not exist anymore
=> chore(jest): remove utilities path from config

docs/_sidebar.md, docs/recipes/README.md, package.json, yarn.lock
Makes the layout nicer on the docsite
=> docs: improve sidebar & bump cli-utils-docsite

components/loader/src/linear-loader/linear-loader.js
This PR adds an `inverted` style option, recently added to the circular loader, to the linear loader.
=> feat(loader): linear loader inverted style

components/sharing-dialog/package.json, components/sharing-dialog/src/__tests__/AccessSelect.test.js, components/sharing-dialog/src/access-select.js, components/sharing-dialog/src/autocomplete/autocomplete.js, components/sharing-dialog/src/dashboard-cascade-sharing-content.js, components/sharing-dialog/src/share-block.js, yarn.lock
Disable form inputs and buttons when offline.
A tooltip is also shown.
=> fix: offline mode, form interaction is disabled

components/tab/src/tab-bar/features/auto_hides_scroll_buttons.feature, components/tab/src/tab-bar/features/auto_hides_scroll_buttons/index.js, components/tab/src/tab-bar/scroll-bar.js, components/tab/src/tab-bar/scroll-button.js, components/tab/src/tab-bar/tab-bar.stories.e2e.js, components/tab/src/tab-bar/tab-bar.stories.js
Closes LIBS-211
([link](https://jira.dhis2.org/browse/LIBS-211))
=> feat(tab bar): add "autoHideScrollButtons" functionality

.github/workflows/dhis2-verify-lib.yml, components/header-bar/i18n/en.pot, scripts/create-artifact.sh, scripts/extract-artifact.sh
Provides a nice speed up:
Upload:
Download:
Upload: 
Download:
=> ci(verify): tar files before uploading artifact

components/sharing-dialog/src/__tests__/SharingDialog.test.js, components/sharing-dialog/src/access-select.js, components/sharing-dialog/src/dashboard-cascade-sharing-content.js, components/sharing-dialog/src/sharing-dialog.js, components/sharing-dialog/src/sharing-dialog.stories.js
* Mainly fixes the escaping issue in the dialog's title.
Before:
After:
* Minor fixes to the tests.
=> fix: sharing dialog bugs

components/tooltip/src/tooltip.test.js, package.json, yarn.lock
This allows us to remove the app-runtime resolutions field. Fixes: https://jira.dhis2.org/browse/LIBS-224
=> fix(deps): update cli-app-scripts

collections/ui/package.json, collections/widgets/package.json, components/header-bar/package.json, components/header-bar/src/features/the_headerbar_contains_a_profile_menu.feature, components/header-bar/src/features/the_headerbar_contains_a_profile_menu/the_user_can_log_out.js, components/header-bar/src/profile/profile-menu.js, components/organisation-unit-tree/package.json, components/sharing-dialog/package.json, package.json, yarn.lock
Backport of #740; part of https://jira.dhis2.org/browse/TECH-682
=> feat(header-bar): clear sensitive caches on logout v6.x

CHANGELOG.md
See here: https://dhis2.slack.com/archives/CBM8LNEQM/p1632314392098100
=> docs(changelog): add note on @dhis2/prop-types change

components/menu/src/flyout-menu/features/position/index.js, components/menu/src/flyout-menu/flyout-menu.js, yarn.lock
This PR adjusts the flyout menu to fix [UX-46](https://jira.dhis2.org/browse/UX-46):
- the `card` component is removed, as this does not have the intended styles.
- `elevation` is updated for the flyout wrapper.
- styles previous applied to the `card` are applied to the flyout wrapper.
=> feat(menu): flyout menu style fixes

components/card/src/card.js
This PR adjusts the `card` component to use the correct `elevation` constant.
=> fix(card): use elevation constant

.github/workflows/dhis2-preview-pr.yml, CODEOWNERS, components/alert/src/alert-bar/icon.js, components/select/src/multi-select/multi-select.js, components/select/src/single-select/single-select.js, package.json, storybook/config/preview.js, yarn.lock
- ci(preview): update to latest workflow
- chore(deps-dev): update cli-style to latest
- style: update code style to latest
=> chore: update workflow and code style

components/button/src/button-strip/button-strip.js
Fixes [LIBS-267](https://jira.dhis2.org/browse/LIBS-267).
=> fix(button): adjust button strip margin between buttons

components/button/src/dropdown-button/dropdown-button.js, components/button/src/dropdown-button/dropdown-button.stories.js
=> refactor(dropdown-button): single click handler

collections/ui/src/index.js, components/organisation-unit-tree/src/index.js, components/organisation-unit-tree/src/organisation-unit-tree/index.js, components/organisation-unit-tree/src/organisation-unit-tree/organisation-unit-tree.js, components/organisation-unit-tree/src/organisation-unit-tree/root-error.js, components/organisation-unit-tree/src/organisation-unit-tree/root-loading.js
I've changed the data-test value of the `RootError` component.
It could be considered a bug fix as it was the same as the data test value of the `RootLoading` component..
=> feat(org unit tree): expose <RootError /> & <RootLoading />

components/button/src/button/button.styles.js
Closes https://jira.dhis2.org/browse/LIBS-285
=> fix(button): remove transitions

components/node/src/toggle.js
Implements [UX-133](https://dhis2.atlassian.net/browse/UX-133)
---
This PR adjusts the design and interaction of the `toggle` element used by the `node` component. 
---
[UX-133]: https://dhis2.atlassian.net/browse/UX-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(node): adjust toggle style and interaction

.github/workflows/dhis2-verify-commits.yml
Update commitlint action to latest.
=> ci(commitlint): update commitlint to v5

components/calendar/src/calendar/calendar-table.js
updates the propTypes of a calendar subcomponent to the correct type
fixes https://dhis2.atlassian.net/browse/DHIS2-14624
=> fix: update wrong propTypes

components/header-bar/src/apps.js, components/header-bar/src/header-bar.js, components/header-bar/src/logo.js, components/header-bar/src/notification-icon.js, components/header-bar/src/notifications.js, components/header-bar/src/online-status.styles.js, components/header-bar/src/profile-menu/profile-menu.js, components/header-bar/src/profile.js
Implements [UX-142](https://dhis2.atlassian.net/browse/UX-142)
---
Improves interaction with clickable elements of the headerbar:
- increase click area of interactive elements
- give interactive elements a `:hover` style
- use consistent `:focus` style
---
---
**Before:**
https://github.com/dhis2/ui/assets/33054985/dd10dde4-538f-49f0-9dee-bfe95838022a
**After:**
https://github.com/dhis2/ui/assets/33054985/3270e794-16a5-4507-ba43-efb6720168be
[UX-142]: https://dhis2.atlassian.net/browse/UX-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
=> fix(headerbar): improve clickable area interactions

docs/docs/principles/icons.md
Fixes broken link to icons storybook example.
---
=> docs: update link to icons storybook

components/button/types/index.d.ts, constants/types/index.d.ts
Minor type fixes in preparation for releasing alpha
=> fix(types): minor type fixes

components/segmented-control/src/segmented-control.js
Small fix to list key in segmented control
=> fix: li key to be unique

components/selector-bar/src/selector-bar-item/selector-bar-item.js, components/selector-bar/src/selector-bar/selector-bar.js, components/selector-bar/types/index.d.ts
Implements [LIBS-570](https://dhis2.atlassian.net/browse/LIBS-570)
---
- SelectorBar has role="toolbar"
- SelectorBar acts as a composite component, a user can tab into SelectorBar
- A user can use left/right arrow keys to move between SelectorBarItem components.
- Pressing the left/right arrow keys will cycle back to the first or last SelectorBarItem, ensuring continuous navigation.
---
[LIBS-570]: https://dhis2.atlassian.net/browse/LIBS-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(selectionBar): accessibility improvements for SelectionBar

components/header-bar/i18n/en.pot, components/header-bar/src/notification-icon.js, components/header-bar/src/notifications.js, components/header-bar/src/profile.js
Implements [LIBS-564](https://dhis2.atlassian.net/browse/LIBS-564)
---
update accessibility for HeaderBar component by Add title and aria-label attributes to icon-only buttons.
[LIBS-564]: https://dhis2.atlassian.net/browse/LIBS-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: improve accessibility of headerbar notification icons and profile

components/user-avatar/src/text-avatar.js, components/user-avatar/src/user-avatar.js, components/user-avatar/types/index.d.ts
Implements [LIBS-573](https://dhis2.atlassian.net/browse/LIBS-573)
---
update aria-label attribute on UserAvatar and TextAvatar to improve accessibility 
[LIBS-573]: https://dhis2.atlassian.net/browse/LIBS-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update user avatar accessibility

.github/workflows/dhis2-verify-lib.yml, README.md, cypress/support/generateTestMatrix.js
**Conditional Recording Triggers**: Implemented conditional recording triggers via commit messages and GitHub labels to ensure that Cypress tests are only recorded when necessary.
**Parallel Execution Strategies**: Refined parallel execution strategies to improve efficiency and resolve test redundancies in GitHub Actions.
**Debugging Enhancements**: Added detailed debugging outputs to help track the dynamic values of the test environment variables and ensure correct parameter passing in the workflow.
**Update Documentation**: Updated the documentation to reflect the changes and ensure clarity on the new CI/CD processes.
**Reduced Cypress Cloud Credit Usage**: By optimising the conditions under which tests are recorded and uploaded to Cypress Cloud, we anticipate a significant reduction in …
=> chore: [DHIS2-17375] optimise Cypress triggers and refine parallel execution in GitHub Actions

components/sharing-dialog/src/modal/modal.js, components/sharing-dialog/src/sharing-dialog.js
Needed for [DHIS2-17276](https://dhis2.atlassian.net/browse/DHIS2-17276)
---
Allow sharing dialog modal to have a data test prop
[DHIS2-17276]: https://dhis2.atlassian.net/browse/DHIS2-17276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add data test prop to sharing dialog

components/calendar/i18n/en.pot, components/calendar/src/calendar-input/calendar-input.js
---
This i18n wraps the "Pick a date" string in CalendarInput to make it translatable
---
=> fix: i18n wrap pick a date

package.json, yarn.lock
Pr to attempt to fix the release of the library: https://github.com/dhis2/ui/actions/runs/10161937412/job/28220159437
=> fix: resolve react version

components/calendar/package.json, components/calendar/src/calendar-input/calendar-input.js, components/calendar/src/calendar/calendar.js, components/calendar/src/stories/calendar-input.prod.stories.js, components/calendar/src/stories/calendar-story-wrapper.js, yarn.lock
updates the stories to showcase how validation works
=> fix: stories for calendar validation

components/calendar/src/calendar-input/calendar-input.js, components/calendar/src/calendar/calendar-container.js, components/calendar/src/calendar/calendar-table-cell.js, components/calendar/src/calendar/calendar-table.js, components/calendar/src/calendar/navigation-container.js, components/calendar/src/stories/calendar-input.prod.stories.js
Prevent handleBlur triggering on empty input focus
=> fix(calendar): prevent handleBlur triggering on empty input focus

components/calendar/src/calendar-input/__tests__/calendar-input.test.js, components/sharing-dialog/types/index.d.ts
This PR adds the dataStore resource to accepted Sharing Dialog types. 
----
=> feat: add datastore sharing dialog type

.github/workflows/dhis2-deploy-netlify.yml
This PR updates the setup-node github action.  Related to #1684
=> ci: update setup-node action
